package org.vaadin.crudui.form.impl.autogenerated;

import java.beans.Introspector;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.data.binder.Setter;
import com.vaadin.flow.data.converter.Converter;
import com.vaadin.flow.function.ValueProvider;

public class Field<B, V, C extends AbstractField<C, V>> {

	public static interface UpdateHandler<B> {
		public void onUpdate(AbstractField fieldToUpdate, B bean);
	}

	public static class Builder<B, V, C extends AbstractField<C, V>> {

		private ValueProvider<B, V> getter;
		private Setter<B, V> setter;
		private Class<V> fieldValueType;
		protected String propertyName;
		private String label;
		private boolean enabled = true;
		private VaadinFieldProvider<?, ?> vaadinFieldProvider;
		private Class<? extends AbstractField> vaadinFieldType;
		private Converter<?, V> converter;
		private List<Builder<B, ?, ?>> valueChangeListeners = new ArrayList<>();
		private UpdateHandler<B> updateHandler;

		public Builder(ValueProvider<B, V> getter, Setter<B, V> setter, Class<V> fieldValueType) {
			this.getter = Objects.requireNonNull(getter, "Getter cannot be null");
			this.setter = Objects.requireNonNull(setter, "Setter cannot be null");
			this.fieldValueType = Objects.requireNonNull(fieldValueType, "Field value type cannot be null");
			this.propertyName = inferPropertyName(getter, setter);
		}

		public Builder(ValueProvider<B, V> getter, Setter<B, V> setter) {
			this.getter = Objects.requireNonNull(getter, "Getter cannot be null");
			this.setter = Objects.requireNonNull(setter, "Setter cannot be null");
			this.propertyName = inferPropertyName(getter, setter);
			this.fieldValueType = (Class<V>) inferFieldValueType(getter, setter);
		}

		public Builder(String propertyName) {
			this.propertyName = Objects.requireNonNull(propertyName, "Property name cannot be null");
		}

		public Builder<B, V, C> label(String label) {
			return caption(label);
		}

		public Builder<B, V, C> caption(String caption) {
			this.label = caption;
			return this;
		}

		public Builder<B, V, C> enabled(boolean enabled) {
			this.enabled = enabled;
			return this;
		}

		public Builder<B, V, C> fieldProvider(VaadinFieldProvider<?, ?> vaadinFieldProvider) {
			this.vaadinFieldProvider = vaadinFieldProvider;
			return this;
		}

		public Builder<B, V, C> fieldType(Class<? extends AbstractField> vaadinFieldType) {
			this.vaadinFieldType = vaadinFieldType;
			return this;
		}

		public Builder<B, V, C> converter(Converter<?, V> converter) {
			this.converter = converter;
			return this;
		}

		public Builder<B, V, C> onValueChangeUpdate(Builder<B, ?, ?> newValueChangeListener) {
			valueChangeListeners.add(newValueChangeListener);
			return this;
		}

		public Builder<B, V, C> onUpdate(UpdateHandler<B> updateHandler) {
			this.updateHandler = updateHandler;
			return this;
		}

		public Field<B, V, C> build() {
			return new Field<>(this);
		}
	}

	public static <B, V, C extends AbstractField<C, V>> Builder<B, V, C> of(
			ValueProvider<B, V> getter, Setter<B, V> setter, Class<V> fieldValueType) {
		return new Builder<>(getter, setter, fieldValueType);
	}

	public static <B, V, C extends AbstractField<C, V>> Builder<B, V, C> of(
			ValueProvider<B, V> getter, Setter<B, V> setter) {
		return new Builder<>(getter, setter);
	}

	public static <B, V, C extends AbstractField<C, V>> Builder<B, V, C> of(
			String propertyName) {
		return new Builder<>(propertyName);
	}

	private static String inferPropertyName(Object getter, Object setter) {
		String methodName = inferMethodName(getter);
		if (methodName == null) {
			methodName = inferMethodName(setter);
		}
		if (methodName == null) {
			return null;
		}

		if (methodName.startsWith("get") && methodName.length() > 3) {
			return Introspector.decapitalize(methodName.substring(3));
		}
		if (methodName.startsWith("set") && methodName.length() > 3) {
			return Introspector.decapitalize(methodName.substring(3));
		}
		if (methodName.startsWith("is") && methodName.length() > 2) {
			return Introspector.decapitalize(methodName.substring(2));
		}

		return methodName;
	}

	private static Class<?> inferFieldValueType(Object getter, Object setter) {
		Method getterMethod = inferMethod(getter);
		if (getterMethod != null) {
			return getterMethod.getReturnType();
		}

		Method setterMethod = inferMethod(setter);
		if (setterMethod != null && setterMethod.getParameterCount() > 0) {
			return setterMethod.getParameterTypes()[0];
		}

		return null;
	}

	private static String inferMethodName(Object lambda) {
		Method method = inferMethod(lambda);
		return method != null ? method.getName() : null;
	}

	private static Method inferMethod(Object lambda) {
		if (lambda == null) {
			return null;
		}

		try {
			Method writeReplace = lambda.getClass().getDeclaredMethod("writeReplace");
			writeReplace.setAccessible(true);
			Object serializedForm = writeReplace.invoke(lambda);
			if (serializedForm instanceof SerializedLambda serializedLambda) {
				String className = serializedLambda.getImplClass().replace('/', '.');
				Class<?> implClass = Class.forName(className);
				for (Method method : implClass.getDeclaredMethods()) {
					if (method.getName().equals(serializedLambda.getImplMethodName())) {
						return method;
					}
				}
			}
		} catch (ReflectiveOperationException ignored) {
			// fall through and let the caller handle missing inference
		}

		return null;
	}

	private final ValueProvider<B, V> getter;
	private final Setter<B, V> setter;
	private final Class<V> fieldValueType;
	private final String propertyName;
	private final String label;
	private final boolean enabled;
	private final VaadinFieldProvider<?, ?> vaadinFieldProvider;
	private final Class<? extends AbstractField> vaadinFieldType;
	private final Converter<?, V> converter;
	private final List<Builder<B, ?, ?>> valueChangeListeners;
	private final UpdateHandler<B> updateHandler;

	private Field(Builder<B, V, C> builder) {
		this.getter = builder.getter;
		this.setter = builder.setter;
		this.fieldValueType = builder.fieldValueType;
		this.propertyName = builder.propertyName;
		this.label = builder.label;
		this.enabled = builder.enabled;
		this.vaadinFieldProvider = builder.vaadinFieldProvider;
		this.vaadinFieldType = builder.vaadinFieldType;
		this.converter = builder.converter;
		this.valueChangeListeners = builder.valueChangeListeners;
		this.updateHandler = builder.updateHandler;
	}

	public ValueProvider<B, V> getGetter() {
		return getter;
	}

	public Setter<B, V> getSetter() {
		return setter;
	}

	public Class<V> getFieldValueType() {
		return fieldValueType;
	}

	public String getPropertyName() {
		return propertyName;
	}

	public String getLabel() {
		return label;
	}

	public String getCaption() {
		return label;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public VaadinFieldProvider<?, ?> getVaadinFieldProvider() {
		return vaadinFieldProvider;
	}

	public Class<? extends AbstractField> getVaadinFieldType() {
		return vaadinFieldType;
	}

	public Converter<?, V> getConverter() {
		return converter;
	}

	public List<Builder<B, ?, ?>> getValueChangeListeners() {
		return valueChangeListeners;
	}

	public UpdateHandler<B> getUpdateHandler() {
		return updateHandler;
	}

}
