package org.vaadin.crudui.form.impl.autogenerated;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.HasValueAndElement;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.data.binder.BeanValidationBinder;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.Setter;
import com.vaadin.flow.data.converter.Converter;
import com.vaadin.flow.function.ValueProvider;

import org.vaadin.crudui.form.CrudForm;

public class Form<B> extends Composite<FormLayout> implements CrudForm<B> {

	private Binder<B> binder;

	public Form(Class<B> domainType, boolean useBeanValidation) {
		if (useBeanValidation) {
			binder = new BeanValidationBinder<>(domainType);
		} else {
			binder = new Binder<>(domainType);
		}
	}

	public Form(Class<B> beanType) {
		this(beanType, false);
	}

	@Override
	public B getValue() {
		return binder.getBean();
	}

	@Override
	public void setValue(B value) {
		binder.setBean(value);
	}

	@Override
	public boolean isReadOnly() {
		return getContent().getChildren()
				.filter(HasValueAndElement.class::isInstance)
				.map(HasValueAndElement.class::cast)
				.filter(field -> !field.isReadOnly())
				.findAny()
				.isEmpty();
	}

	@Override
	public void setReadOnly(boolean readOnly) {
		getContent().getChildren()
				.map(HasValueAndElement.class::cast)
				.forEach(field -> field.setReadOnly(readOnly));
	}

	@Override
	public boolean isValid() {
		return binder.isValid();
	}

	public <C extends AbstractField<C, V>, V> void add(AbstractField<C, V> field,
			ValueProvider<B, V> getter, Setter<B, V> setter) {
		add(field, getter, setter, null);
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	public void add(AbstractField<?, ?> field,
			ValueProvider<B, ?> getter, Setter<B, ?> setter, Converter<?, ?> converter) {
		if (converter != null) {
			binder.forField(field).withConverter((Converter) converter).bind(getter, setter);
		} else {
			binder.forField(field).bind((ValueProvider) getter, (Setter) setter);
		}
		getContent().add(field);
	}

	public <C extends AbstractField<C, V>, V> void add(AbstractField<C, V> field,
			String javaPropertyName) {
		add(field, javaPropertyName, null);
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	public void add(AbstractField<?, ?> field,
			String javaPropertyName, Converter<?, ?> converter) {
		if (converter != null) {
			binder.forField(field).withConverter((Converter) converter).bind(javaPropertyName);
		} else {
			binder.forField(field).bind(javaPropertyName);
		}
		getContent().add(field);
	}

}
