package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.splitlayout.SplitLayout.Orientation;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;

/**
 * Test view showcasing the new fluent form() and layout() entry points in Crud.
 *
 * Demonstrates:
 * - form() method for setting custom form factories
 * - layout() method for setting custom layout implementations
 * - Method chaining with form() and layout()
 * - Fluent API as alternative to setCrudFormFactory() and setCrudLayout()
 */
@Route(value = "requirement-0007")
public class Requirement0007 extends VerticalLayout {

    public Requirement0007(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        // Example 1: Using form() with AutoGeneratedFormFactory
        Crud<User> crudWithFluentForm = Crud.of(User.class)
            .form(AutoGeneratedFormFactory.of(User.class).useBeanValidation())
            .onRead(userService::findAll)
            .onCreate(userService::save)
            .onUpdate(userService::save)
            .onDelete(userService::delete)
            .build();

        // Example 2: Using layout() with SplitCrudLayout (horizontal)
        Crud<User> crudWithFluentLayout = Crud.of(User.class)
            .layout(new SplitCrudLayout<>(Orientation.HORIZONTAL))
            .onRead(userService::findAll)
            .onCreate(userService::save)
            .onUpdate(userService::save)
            .onDelete(userService::delete)
            .build();

        // Example 3: Using both form() and layout() together
        Crud<User> crudWithBothFluent = Crud.of(User.class)
            .form(AutoGeneratedFormFactory.of(User.class).useBeanValidation())
            .layout(new SplitCrudLayout<>(Orientation.VERTICAL))
            .onRead(userService::findAll)
            .onCreate(userService::save)
            .onUpdate(userService::save)
            .onDelete(userService::delete)
            .build();

        add(
            new H3("CRUD with fluent form()"),
            crudWithFluentForm,
            new H3("CRUD with fluent layout() - Horizontal"),
            crudWithFluentLayout,
            new H3("CRUD with both fluent form() and layout() - Vertical"),
            crudWithBothFluent
        );
    }
}
