package org.vaadin.crudui.demo.ui.view.test;

import java.util.List;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.Crud;
import org.vaadin.crudui.CrudOperation;
import org.vaadin.crudui.demo.entity.Group;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui.form.impl.autogenerated.Field;
import org.vaadin.crudui.form.impl.autogenerated.field.provider.MultiSelectComboBoxProvider;
import org.vaadin.crudui.list.impl.GridList;

@Route(value = "requirement-0008")
public class Requirement0008 extends VerticalLayout {

    public Requirement0008(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        AutoGeneratedFormFactory<User> operationAwareFormFactory = AutoGeneratedFormFactory.of(User.class)
                .fields(
                        Field.of(User::getName, User::setName).caption("Name"),
                        Field.of("email").caption("Email"),
                        Field.of("maritalStatus").caption("Marital status"))
                .fieldsFor(CrudOperation.READ,
                        Field.of("name").caption("Name"),
                        Field.of(User::getEmail, User::setEmail).caption("Email"),
                        Field.of("maritalStatus").caption("Marital status"))
                .fieldsFor(CrudOperation.DELETE,
                        Field.of(User::getName, User::setName).caption("Name"),
                        Field.of("email").caption("Email"))
                .additionalFieldsFor(CrudOperation.CREATE,
                        Field.of(User::getPassword, User::setPassword).caption("Password"),
                        Field.of("birthDate").caption("Birth date"))
                .additionalFieldsFor(CrudOperation.UPDATE,
                        Field.of(User::getActive, User::setActive).caption("Active"),
                        Field.of("groups")
                                .caption("Groups")
                                .fieldProvider(new MultiSelectComboBoxProvider<>(ignored -> groupService.findAll(),
                                        Group::getName)))
                .captions("Create user", "Edit user")
                .useBeanValidation();

        Crud<User> crud = Crud.of(User.class)
                .list(GridList.of(User.class))
                .form(operationAwareFormFactory)
                .onCreate(userService::save)
                .onRead(userService::findAll)
                .onUpdate(userService::save)
                .onDelete(userService::delete)
                .viewBeforeEdit(true)
                .build();

        User sampleUser = sampleUser(userService.findAll());

        add(
                new H3("Operation-aware form factory"),
                new Paragraph(
                        "Default fields are shared, while READ, CREATE, UPDATE, and DELETE can each override or extend the field set."),
                crud,
                new H3("Direct operation previews"),
                operationPreview("READ", operationAwareFormFactory, sampleUser, CrudOperation.READ),
                operationPreview("CREATE", operationAwareFormFactory, new User(), CrudOperation.CREATE),
                operationPreview("UPDATE", operationAwareFormFactory, sampleUser, CrudOperation.UPDATE),
                operationPreview("DELETE", operationAwareFormFactory, sampleUser, CrudOperation.DELETE));
    }

    private User sampleUser(List<User> users) {
        return users.isEmpty() ? new User() : users.getFirst();
    }

    private Component operationPreview(String title, AutoGeneratedFormFactory<User> formFactory, User user,
            CrudOperation operation) {
        VerticalLayout preview = new VerticalLayout();
        preview.setPadding(true);
        preview.setSpacing(true);
        preview.add(new H3(title), (Component) formFactory.build(user, operation));
        return preview;
    }

}
