package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;

/**
 * Test view showcasing the simple Crud.of() API with default components.
 *
 * Demonstrates:
 * - Creating a CRUD component from a bean class
 * - Using default GridList + SplitCrudLayout + AutoGeneratedFormFactory
 * - Using sensible defaults with no manual glue code
 * - Data provider setup
 */
@Route(value = "requirement-0001")
public class Requirement0001 extends VerticalLayout {

    public Requirement0001(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);

        Crud<User> userCrud = Crud.of(User.class).build();

        // Add the CRUD component to layout
        add(userCrud);
    }
}
