package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.Crud;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui.layout.impl.DialogCrudLayout;
import org.vaadin.crudui.list.impl.GridList;

/**
 * Test view demonstrating requirement-0010:
 * Dialog-based CRUD layout that shows a CrudList with action components on top
 * and displays forms in a modal dialog.
 */
@Route(value = "requirement-0010")
public class Requirement0010 extends VerticalLayout {

    public Requirement0010(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        // Demonstrating dialog-based layout
        Crud<User> crud = Crud.of(User.class)
                .list(GridList.of(User.class))
                .form(AutoGeneratedFormFactory.of(User.class)
                        .captions("Create User", "Edit User"))
                .layout(DialogCrudLayout.of(User.class)
                        .dialogWidth("50vw")
                        .dialogDraggable(true)
                        .dialogResizable(true))
                .onCreate(userService::save)
                .onRead(userService::findAll)
                .onUpdate(userService::save)
                .onDelete(userService::delete)
                .build();

        add(
                new H3("Dialog-based CRUD Layout"),
                crud);
        expand(crud);
    }

}
