package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.Technology;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.TechnologyService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field;
import org.vaadin.crudui2.list.impl.GridList;

@Route(value = "requirement-0009")
public class Requirement0009 extends VerticalLayout {

    public Requirement0009(UserService userService, GroupService groupService, TechnologyService technologyService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        TreeGrid<Technology> treeGrid = new TreeGrid<>();
        treeGrid.setSizeFull();
        treeGrid.addHierarchyColumn(Requirement0009::technologyName).setHeader("Name");
        treeGrid.addColumn(Requirement0009::technologyVersion).setHeader("Version");
        treeGrid.addColumn(Requirement0009::technologyLastPatchedAt).setHeader("Last Patched");
        treeGrid.setItems(technologyService.findRoots(), technologyService::findChildren);

        Crud<Technology> technologyCrud = Crud.of(Technology.class)
                .list(GridList.of(Technology.class)
                        .grid(treeGrid))
                .form(AutoGeneratedFormFactory.of(Technology.class)
                        .fields(
                                Field.of("name").caption("Name"),
                                Field.of("version").caption("Version"),
                                Field.of("lastPatchedAt").caption("Last patched"),
                                Field.of("description").caption("Description"))
                        .captions("Create technology", "Edit technology")
                        .useBeanValidation())
                .onCreate(technologyService::save)
                .onUpdate(technologyService::save)
                .onDelete(technologyService::delete)
                .build();

        add(
                new H3("TreeGrid as custom Grid in GridList"),
                technologyCrud);
        expand(technologyCrud);
    }

        private static String technologyName(Technology technology) {
                return technology.getName();
        }

        private static Double technologyVersion(Technology technology) {
                return technology.getVersion();
        }

        private static Object technologyLastPatchedAt(Technology technology) {
                return technology.getLastPatchedAt();
        }
}
