package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;
import org.vaadin.crudui2.CrudOperation;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.list.impl.GridList;

@Route(value = "requirement-0005")
public class Requirement0005 extends VerticalLayout {

    public Requirement0005(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);

        Crud<User> userCrud = Crud.of(User.class)
                .list(GridList.of(User.class))
                .form(AutoGeneratedFormFactory.of(User.class)
                        .captions("Create User", "Update User"))
                .onCreate(userService::save)
                .onRead(userService::findAll)
                .onUpdate(userService::save)
                .onDelete(userService::delete)
                .button(CrudOperation.CREATE).label("Add User", VaadinIcon.PLUS.create(), ButtonVariant.LUMO_PRIMARY)
                .button(CrudOperation.UPDATE).label("Persist", VaadinIcon.CHECK.create(), ButtonVariant.LUMO_PRIMARY)
                .button(CrudOperation.DELETE).label("Remove", VaadinIcon.TRASH.create(), ButtonVariant.LUMO_ERROR)
                .button(CrudOperation.READ).label("Back", VaadinIcon.CLOSE_SMALL.create(), ButtonVariant.LUMO_TERTIARY)
                .deleteConfirmation().texts(
                        "Delete selected user?",
                        "This will permanently remove the selected user.",
                        "Delete user",
                        "Keep user")
                .viewBeforeEdit(true)
                .build();

        add(userCrud);
    }
}
