package org.vaadin.crudui.demo.ui.view.test;

import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.splitlayout.SplitLayout.Orientation;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;

/**
 * Test view demonstrating requirement-0007:
 * Fluent form() and layout() entry points that return appropriate builders for method chaining.
 */
@Route(value = "requirement-0007")
public class Requirement0007 extends VerticalLayout {

    public Requirement0007(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        // Demonstrating fluent form(), layout(), and list() builders
        Crud<User> crud = Crud.of(User.class)
            .form(AutoGeneratedFormFactory.of(User.class)
                .captions("Create User", "Edit User"))
            .layout(SplitCrudLayout.of(User.class)
                .orientation(Orientation.HORIZONTAL))
            .onRead(userService::findAll)
            .onCreate(userService::save)
            .onUpdate(userService::save)
            .onDelete(userService::delete)
            .build();

        add(
            new H3("Fluent form() and layout() entry points"),
            crud
        );
    }
}
