package org.vaadin.crudui.demo.ui.view.test;

import java.math.BigDecimal;

import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.converter.StringToBigDecimalConverter;
import com.vaadin.flow.data.converter.StringToIntegerConverter;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.Crud;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field;

/**
 * Test view demonstrating requirement-0013: Field.converter(...) is applied to binder bindings.
 */
@Route(value = "requirement-0013")
@SuppressWarnings({ "null", "unchecked" })
public class Requirement0013 extends VerticalLayout {

    public Requirement0013(UserService userService, GroupService groupService) {
        setSizeFull();
        setPadding(true);
        setSpacing(true);

        Crud<User> crud = Crud.of(User.class)
                .form(AutoGeneratedFormFactory.of(User.class)
                        .fields(
                                Field.of(User::getSalary, User::setSalary, BigDecimal.class)
                                        .label("Salary (Text -> BigDecimal)")
                                        .fieldProvider(bean -> new TextField())
                                        .converter(new StringToBigDecimalConverter(
                                                "Invalid salary. Cannot convert to BigDecimal.")),
                                Field.of("phoneNumber")
                                        .label("Phone Number (Text -> Integer)")
                                        .fieldType(TextField.class)
                                        .converter((com.vaadin.flow.data.converter.Converter<?, Object>)
                                                (com.vaadin.flow.data.converter.Converter<?, ?>) new StringToIntegerConverter(
                                                        "Invalid phone number. Cannot convert to Integer."))))
                .onRead(userService::findAll)
                .onCreate(userService::save)
                .onUpdate(userService::save)
                .onDelete(userService::delete)
                .build();

        add(
                new H3("Requirement 0013 - Converter support in auto-generated forms"),
                new Paragraph("Edit a user and enter an invalid value in Salary or Phone Number. "
                        + "The form becomes invalid and save is prevented by binder validation."),
                crud);
        expand(crud);
    }
}
