package org.vaadin.crudui2.form.impl.autogenerated;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyName;
import com.fasterxml.jackson.databind.introspect.BasicBeanDescription;
import com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition;
import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.Focusable;
import com.vaadin.flow.component.HasLabel;
import com.vaadin.flow.component.shared.HasClearButton;
import com.vaadin.flow.data.provider.HasListDataView;
import com.vaadin.flow.shared.util.SharedUtil;

import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.CrudFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field.Builder;
import org.vaadin.crudui2.form.impl.autogenerated.Field.UpdateHandler;
import org.vaadin.crudui2.form.impl.autogenerated.field.provider.TypeBasedFieldProvider;

public class AutoGeneratedFormFactory<B> implements CrudFormFactory<B> {

	private Class<B> domainType;
	private List<Field.Builder<?, ?, ?>> formFieldBuilders = new ArrayList<>();
	private boolean useBeanValidation;
	private String createCaption = "Add";
	private String updateCaption = "Update";

	public static <B> AutoGeneratedFormFactory<B> of(Class<B> domainType) {
		return new AutoGeneratedFormFactory<>(domainType);
	}

	private AutoGeneratedFormFactory(Class<B> domainType) {
		this.domainType = domainType;
		autoGenerateFormFieldBuilders();
	}

	public <V, C extends AbstractField<C, V>> AutoGeneratedFormFactory<B> add(
			Field.Builder<B, ?, ?> fieldBuilder) {
		formFieldBuilders.add(fieldBuilder);
		return this;
	}

	public AutoGeneratedFormFactory<B> fields(Field.Builder<?, ?, ?>... newFormFieldBuilders) {
		formFieldBuilders.clear();
		formFieldBuilders.addAll(List.of(newFormFieldBuilders));
		return this;
	}

	public AutoGeneratedFormFactory<B> replace(String propertyName, Field.Builder<?, ?, ?> newFormFieldBuilder) {
		formFieldBuilders.replaceAll(builder -> {
			if (propertyName.equals(builder.propertyName)) {
				return newFormFieldBuilder;
			}
			return builder;
		});
		return this;
	}

	public AutoGeneratedFormFactory<B> useBeanValidation() {
		useBeanValidation = true;
		return this;
	}

	public AutoGeneratedFormFactory<B> captions(String createCaption, String updateCaption) {
		this.createCaption = createCaption;
		this.updateCaption = updateCaption;
		return this;
	}

	public String getCreateCaption() {
		return createCaption;
	}

	public String getUpdateCaption() {
		return updateCaption;
	}

	@Override
	public CrudForm<B> build(final B bean) {
		Form<B> form = new Form<>(domainType, useBeanValidation);
		form.setValue(bean);

		var vaadinFieldByBuilder = new HashMap<Builder<?, ?, ?>, AbstractField<?, ?>>();
		var formFieldByVaadinField = new HashMap<AbstractField<?, ?>, Field<B, ?, ?>>();
		var vaadinFieldByFormField = new LinkedHashMap<Field<B, ?, ?>, AbstractField<?, ?>>();
		var notifiers = new HashMap<AbstractField<?, ?>, List<Builder<B, ?, ?>>>();

		formFieldBuilders.forEach(builder -> {
			try {
				Field formField = builder.build();
				VaadinFieldProvider fieldProvider = formField.getVaadinFieldProvider();

				if (fieldProvider == null) {
					fieldProvider = new TypeBasedFieldProvider<>(formField.getVaadinFieldType(),
							formField.getFieldValueType(), formField.getPropertyName());
				}

				AbstractField vaadinField = fieldProvider.buildField(bean);
				configureVaadinField(vaadinField, formField);
				updateVaadinField(vaadinField, formField, bean);

				if (formField.getGetter() != null) {
					form.add(vaadinField, formField.getGetter(), formField.getSetter());

				} else {
					form.add(vaadinField, formField.getPropertyName());
				}

				if (!formField.getValueChangeListeners().isEmpty()) {
					notifiers.put(vaadinField, formField.getValueChangeListeners());
				}

				vaadinFieldByBuilder.put(builder, vaadinField);
				formFieldByVaadinField.put(vaadinField, formField);
				vaadinFieldByFormField.put(formField, vaadinField);

			} catch (TypeBasedFieldProvider.UnsupportedFieldTypeException ignored) {
				// no field is created
			}
		});

		addNotifiers(form, vaadinFieldByBuilder, formFieldByVaadinField, notifiers);
		focusOnFirstField(vaadinFieldByFormField.values());

		return form;
	}

	private void configureVaadinField(AbstractField<?, ?> vaadinField, Field<B, ?, ?> formField) {
		if (HasLabel.class.isAssignableFrom(vaadinField.getClass())) {
			((HasLabel) vaadinField).setLabel(formField.getLabel());
		}

		if (HasClearButton.class.isAssignableFrom(vaadinField.getClass())) {
			((HasClearButton) vaadinField).setClearButtonVisible(true);
		}

		vaadinField.setEnabled(formField.isEnabled());
	}

	private void updateVaadinField(AbstractField<?, ?> vaadinField, Field<B, ?, ?> formField, B bean) {
		if (formField.getUpdateHandler() != null) {
			formField.getUpdateHandler().onUpdate(vaadinField, bean);
		} else {
			Class<?> fieldValueType = formField.getFieldValueType();
			if (fieldValueType != null) {
				if (fieldValueType.isEnum() && HasListDataView.class.isAssignableFrom(vaadinField.getClass())) {
					List<?> items = Arrays.asList(fieldValueType.getEnumConstants());
					((HasListDataView) vaadinField).setItems(items);
				}
			} else if (formField.getPropertyName() != null) {
				ObjectMapper mapper = new ObjectMapper();
				JavaType javaType = mapper.getTypeFactory().constructType(bean.getClass());
				var beanDescription = (BasicBeanDescription) mapper.getSerializationConfig().introspect(javaType);
				BeanPropertyDefinition property = beanDescription
						.findProperty(new PropertyName(formField.getPropertyName()));
				Class<?> propertyType = property.getRawPrimaryType();
				if (propertyType.isEnum() && HasListDataView.class.isAssignableFrom(vaadinField.getClass())) {
					List<?> items = Arrays.asList(propertyType.getEnumConstants());
					((HasListDataView) vaadinField).setItems(items);
				}
			}
		}
	}

	private void addNotifiers(Form<B> form, Map<Builder<?, ?, ?>, AbstractField<?, ?>> vaadinFieldByBuilder,
			Map<AbstractField<?, ?>, Field<B, ?, ?>> formFieldByVaadinField,
			Map<AbstractField<?, ?>, List<Builder<B, ?, ?>>> notifiers) {
		notifiers.forEach((vaadinFieldNotifier, builderListeners) -> {
			vaadinFieldNotifier.addValueChangeListener(event -> {
				builderListeners.forEach(builderListener -> {
					B value = form.getValue();
					AbstractField<?, ?> vaadinField = vaadinFieldByBuilder.get(builderListener);
					Field formField = formFieldByVaadinField.get(vaadinField);
					UpdateHandler<B> updateHandler = formField.getUpdateHandler();
					if (updateHandler != null) {
						updateHandler.onUpdate(vaadinField, value);
					}
				});
			});
		});
	}

	private void focusOnFirstField(Collection<AbstractField<?, ?>> vaadinFields) {
		vaadinFields.stream()
				.filter(field -> !field.isReadOnly())
				.filter(field -> Focusable.class.isAssignableFrom(field.getClass()))
				.findFirst()
				.map(Focusable.class::cast)
				.ifPresent(Focusable::focus);
	}

	private void autoGenerateFormFieldBuilders() {
		ObjectMapper mapper = new ObjectMapper();
		JavaType javaType = mapper.getTypeFactory().constructType(domainType);
		var beanDescription = (BasicBeanDescription) mapper.getSerializationConfig().introspect(javaType);
		beanDescription.findProperties().forEach(property -> {
			String propertyName = property.getName();
			var fieldBuilder = Field.of(propertyName);
			fieldBuilder.label(SharedUtil.propertyIdToHumanFriendly(propertyName));
			formFieldBuilders.add(fieldBuilder);
		});
	}

}
