package org.vaadin.crudui2.form.impl.autogenerated;

import java.io.Serializable;

import com.vaadin.flow.component.AbstractField;

@FunctionalInterface
public interface VaadinFieldProvider<B, C extends AbstractField<?, ?>> extends Serializable {

	C buildField(B bean);

}
