package org.vaadin.crudui2;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.CrudFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.layout.CrudLayout;
import org.vaadin.crudui2.layout.CrudLayoutFactory;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;
import org.vaadin.crudui2.layout.impl.DialogCrudLayout;
import org.vaadin.crudui2.list.CrudList;
import org.vaadin.crudui2.list.CrudListFactory;
import org.vaadin.crudui2.data.provider.SimpleBackendDataProvider;
import org.vaadin.crudui2.list.impl.GridList;

import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumMap;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Supplier;
import com.vaadin.flow.data.provider.DataProvider;

/**
 * A fluent CRUD component factory. Creates a fully functional CRUD UI from a Java bean class
 * with sensible defaults: GridList + SplitCrudLayout + AutoGeneratedFormFactory.
 *
 * Usage with lambda methods:
 * <pre>
 * Crud&lt;User&gt; crud = Crud.of(User.class)
 *     .list(GridList.of(User.class))
 *     .onRead(userService::findAll)
 *     .onCreate(userService::save)
 *     .onUpdate(userService::save)
 *     .onDelete(userService::delete)
 *     .build();
 * </pre>
 *
 * @param <B> The bean type
 */
public class Crud<B> extends Composite<VerticalLayout> {

    private final Class<B> beanType;
    private CrudList<B> crudList;
    private CrudLayout<B> crudLayout;
    private CrudFormFactory<B> formFactory;
    private CrudForm<B> form;
    private DataProvider<B, ?> readDataProvider;
    private Consumer<B> createOperation;
    private Consumer<B> updateOperation;
    private Consumer<B> deleteOperation;
    private B selectedBean;
    private boolean isCreating;
    private boolean built = false;
    private Button createButton;
    private Button deleteButton;
    private Button saveButton;
    private Button cancelButton;
    private Button updateButton;
    private boolean viewBeforeEdit = false;
    private boolean createOperationVisible = true;
    private boolean updateOperationVisible = true;
    private boolean deleteOperationVisible = true;
    private boolean suppressSelectionEvents = false;
    private final EnumMap<CrudOperation, ButtonConfig> crudButtonConfigs = new EnumMap<>(CrudOperation.class);
    private final EnumMap<CrudOperation, ButtonConfig> formButtonConfigs = new EnumMap<>(CrudOperation.class);
    private String deleteConfirmationHeader = "Delete item?";
    private String deleteConfirmationText = "Are you sure you want to delete this item?";
    private String deleteConfirmationConfirmText = "Delete";
    private String deleteConfirmationCancelText = "Cancel";
    private final List<Component> filterComponents = new ArrayList<>();
    private Consumer<B> saveSuccessCallback;
    private Consumer<B> deleteSuccessCallback;
    private Consumer<Throwable> operationErrorCallback;


    private Crud(Class<B> beanType) {
        this.beanType = beanType;
        this.isCreating = false;

        // Initialize the root VerticalLayout
        getContent().setSizeFull();
        getContent().setPadding(false);

        initializeDefaultButtonConfigs();
    }

    /**
     * Creates a new Crud instance for the specified bean class.
     *
     * @param beanType The Java bean class
     * @param <B>      The bean type
     * @return A new Crud instance with default components
     */
    public static <B> Crud<B> of(Class<B> beanType) {
        Crud<B> crud = new Crud<>(beanType);
        crud.initializeDefaults();
        return crud;
    }

    private void initializeDefaults() {
        // Create default Grid with auto-detected columns
        Grid<B> grid = new Grid<>(beanType, true);

        // Wrap in GridList using fluent builder
        this.crudList = GridList.of(beanType).grid(grid).build();

        // Create default layout using fluent builder
        this.crudLayout = SplitCrudLayout.of(beanType).build();
        this.crudLayout.setCrudList(crudList);

        // Create default form factory
        this.formFactory = AutoGeneratedFormFactory.of(beanType).useBeanValidation();

        // Add the layout to the root content
        getContent().add((Component) crudLayout);
    }

    /**
     * Sets the create operation (lambda approach).
     *
     * @param createOperation A consumer that saves the new bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onCreate(Consumer<B> createOperation) {
        this.createOperation = createOperation;
        return this;
    }

    /**
     * Sets the update operation (lambda approach).
     *
     * @param updateOperation A consumer that updates the bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onUpdate(Consumer<B> updateOperation) {
        this.updateOperation = updateOperation;
        return this;
    }

    /**
     * Sets the delete operation (lambda approach).
     *
     * @param deleteOperation A consumer that deletes the bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onDelete(Consumer<B> deleteOperation) {
        this.deleteOperation = deleteOperation;
        return this;
    }

    /**
     * Sets the read operation using a Vaadin {@link DataProvider}.
     *
     * @param dataProvider The data provider used by the configured list
     * @return This Crud instance for chaining
     */
    public Crud<B> onRead(DataProvider<B, ?> dataProvider) {
        this.readDataProvider = dataProvider;
        this.crudList.setDataProvider(dataProvider);
        return this;
    }

    /**
     * Sets the read operation using a supplier that returns all current items.
     *
     * @param itemsSupplier Supplier returning the current collection of beans
     * @return This Crud instance for chaining
     */
    public Crud<B> onRead(Supplier<? extends Collection<B>> itemsSupplier) {
        return onRead(new SimpleBackendDataProvider<>(itemsSupplier::get));
    }

    /**
     * Enables or disables the view-before-edit mode.
     * When enabled, forms are shown in read-only mode with an "Update" button to enable editing.
     * When disabled (default), forms are shown in editable mode immediately.
     *
     * @param viewBeforeEdit true to show read-only forms first, false for immediate edit mode
     * @return This Crud instance for chaining
     */
    public Crud<B> viewBeforeEdit(boolean viewBeforeEdit) {
        this.viewBeforeEdit = viewBeforeEdit;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the create operation is visible.
     *
     * @param visible true to show create operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> createOperationVisible(boolean visible) {
        this.createOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the update operation is visible.
     *
     * @param visible true to show update operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> updateOperationVisible(boolean visible) {
        this.updateOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the delete operation is visible.
     *
     * @param visible true to show delete operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> deleteOperationVisible(boolean visible) {
        this.deleteOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Sets the form factory.
     *
     * @param factory The form factory to use
     * @return This Crud instance for chaining
     */
    public Crud<B> form(CrudFormFactory<B> factory) {
        this.formFactory = factory;
        return this;
    }

    /**
     * Adds a filter component to the active layout.
     *
     * @param component The filter component to add
     * @return This Crud instance for chaining
     */
    public Crud<B> addFilterComponent(Component component) {
        this.filterComponents.add(component);
        this.crudLayout.addFilterComponent(component);
        return this;
    }

    /**
     * Sets an optional callback invoked after successful create or update operations.
     *
     * @param callback Callback receiving the saved bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onSaveSuccess(Consumer<B> callback) {
        this.saveSuccessCallback = callback;
        return this;
    }

    /**
     * Sets an optional callback invoked after a successful delete operation.
     *
     * @param callback Callback receiving the deleted bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onDeleteSuccess(Consumer<B> callback) {
        this.deleteSuccessCallback = callback;
        return this;
    }

    /**
     * Sets an optional callback invoked when create, update, or delete operations fail.
     *
     * @param callback Callback receiving the operation error
     * @return This Crud instance for chaining
     */
    public Crud<B> onOperationError(Consumer<Throwable> callback) {
        this.operationErrorCallback = callback;
        return this;
    }

    /**
     * Returns a builder for configuring delete confirmation dialog settings.
     *
     * @return A DeleteConfirmationBuilder for chaining delete confirmation configuration
     */
    public DeleteConfirmationBuilder deleteConfirmation() {
        return new DeleteConfirmationBuilder();
    }

    /**
     * Returns a builder for configuring buttons by CRUD operation.
     *
     * @param operation The CRUD operation whose button(s) to configure
     * @return A ButtonBuilder for chaining button configuration
     */
    public ButtonBuilder button(CrudOperation operation) {
        return new ButtonBuilder(operation);
    }

    /**
     * Sets the list implementation using a factory.
     *
     * @param listFactory The list factory
     * @return This Crud instance for chaining
     */
    public Crud<B> list(CrudListFactory<B> listFactory) {
        this.crudList = listFactory.build();
        if (readDataProvider != null) {
            this.crudList.setDataProvider(readDataProvider);
        }
        this.crudLayout.setCrudList(this.crudList);
        applyOperationVisibility();
        return this;
    }

    /**
     * Overrides the default layout implementation using a factory.
     *
     * @param layoutFactory The layout factory
     * @return This Crud instance for chaining
     */
    public Crud<B> layout(CrudLayoutFactory<B> layoutFactory) {
        // Remove old layout from root if it exists
        if (this.crudLayout != null) {
            getContent().remove((Component) this.crudLayout);
        }

        // Build the new layout
        this.crudLayout = layoutFactory.build();

        // Set the current crudList on the new layout
        this.crudLayout.setCrudList(this.crudList);

        for (Component filterComponent : filterComponents) {
            this.crudLayout.addFilterComponent(filterComponent);
        }

        // Add the new layout to the root
        getContent().add((Component) this.crudLayout);

        return this;
    }



    /**
     * Builds and returns the CRUD component ready to be added to a layout.
     * Wires up all listeners and interactions.
     *
     * @return This Crud instance as a Vaadin Component
     */
    public Crud<B> build() {
        if (built) {
            return this;
        }
        built = true;

        // Create action buttons before selection listeners so enable state can be updated consistently
        createButton = new Button("Create", e -> {
            try {
                // Entering create mode must clear list selection and disable update/delete actions.
                if (deleteButton != null) {
                    deleteButton.setEnabled(false);
                }
                if (updateButton != null) {
                    updateButton.setEnabled(false);
                }

                clearListSelectionWithoutEvents();

                selectedBean = beanType.getDeclaredConstructor().newInstance();
                isCreating = true;
                showForm(selectedBean);
            } catch (Exception ex) {
                suppressSelectionEvents = false;
                throw new RuntimeException("Failed to create new instance of " + beanType.getName(), ex);
            }
        });

        deleteButton = new Button("Delete", e -> onDeleteClicked());
        deleteButton.setEnabled(false);

        applyCrudButtonConfig(createButton, CrudOperation.CREATE);
        applyCrudButtonConfig(deleteButton, CrudOperation.DELETE);

        // Create "Update" button - available for all layouts
        updateButton = new Button("Update", e -> onUpdateClicked());
        updateButton.setEnabled(false);
        applyCrudButtonConfig(updateButton, CrudOperation.UPDATE);

        // Wire item selection listener
        crudList.addItemSelectedListener(bean -> {
            if (suppressSelectionEvents) {
                return;
            }

            if (bean != null) {
                selectedBean = bean;
                isCreating = false;
                if (deleteOperationVisible) {
                    deleteButton.setEnabled(true);
                }
                if (updateButton != null && updateOperationVisible) {
                    updateButton.setEnabled(true);
                }
                // Only auto-display form for non-dialog layouts (e.g., SplitCrudLayout)
                // For DialogCrudLayout, the form is only shown when buttons are clicked
                boolean isDialogLayout = crudLayout instanceof DialogCrudLayout;
                if (!isDialogLayout) {
                    showForm(bean);
                }
            } else {
                deleteButton.setEnabled(false);
                if (updateButton != null) {
                    updateButton.setEnabled(false);
                }
                hideForm();
            }
        });

        // Add Create, Update (if enabled), and Delete buttons to layout in order
        crudLayout.addCrudActionComponent(createButton);

        // Add Update button to layout if updateOperationVisible is enabled
        if (updateButton != null && updateOperationVisible) {
            crudLayout.addCrudActionComponent(updateButton);
        }

        crudLayout.addCrudActionComponent(deleteButton);
        applyOperationVisibility();

        return this;
    }

    private void showForm(B bean) {
        CrudOperation operation = isCreating ? CrudOperation.CREATE
                : (viewBeforeEdit || !updateOperationVisible ? CrudOperation.READ : CrudOperation.UPDATE);

        showForm(bean, operation);
    }

    private void showForm(B bean, CrudOperation operation) {
        // Update the form
        form = formFactory.build(bean, operation);
        isCreating = operation == CrudOperation.CREATE;

        crudLayout.hideForm();

        // Lazy-create buttons on first use (they're reused across form displays)
        if (saveButton == null) {
            saveButton = new Button("Save", e -> onSaveClicked());
            cancelButton = new Button("Cancel", e -> hideForm());
        }

        // Determine if form should be read-only
        boolean shouldBeReadOnly = operation == CrudOperation.READ;
        form.setReadOnly(shouldBeReadOnly);

        // Show form and add action buttons
        crudLayout.showCrudForm(form);
        crudLayout.setFormActionCaption(shouldBeReadOnly ? null : (isCreating ? formFactory.getCreateCaption() : formFactory.getUpdateCaption()));

        if (shouldBeReadOnly) {
            applyFormButtonConfig(cancelButton, CrudOperation.READ);
            // Show only Cancel button in read-only mode (Update button is in layout)
            crudLayout.addFormActionComponent(cancelButton);
        } else {
            applyFormButtonConfig(saveButton, isCreating ? CrudOperation.CREATE : CrudOperation.UPDATE);
            applyFormButtonConfig(cancelButton, CrudOperation.READ);
            // Show Save/Cancel buttons in edit mode
            crudLayout.addFormActionComponent(saveButton);
            crudLayout.addFormActionComponent(cancelButton);
        }
    }

    private void onSaveClicked() {
        if (!form.isValid()) {
            return;
        }

        B savedBean = form.getValue();

        boolean success;
        if (isCreating) {
            success = executeOperation(createOperation, savedBean,
                    "Create operation is not set. Cannot create bean.");
        } else {
            success = executeOperation(updateOperation, savedBean,
                    "Update operation is not set. Cannot update bean.");
        }

        if (!success) {
            return;
        }

        isCreating = false;

        // Refresh the list to show updated data
        crudList.refreshAllItems();

        if (saveSuccessCallback != null) {
            saveSuccessCallback.accept(savedBean);
        }

        // Hide form after save
        hideForm();
    }

    private void onDeleteClicked() {
        if (selectedBean == null) {
            return;
        }

        B beanToDelete = selectedBean;
        ConfirmDialog confirmDialog = new ConfirmDialog();
        confirmDialog.setHeader(deleteConfirmationHeader);
        confirmDialog.setText(deleteConfirmationText);
        confirmDialog.setCancelable(true);
        confirmDialog.setCancelText(deleteConfirmationCancelText);
        confirmDialog.setConfirmText(deleteConfirmationConfirmText);
        confirmDialog.setConfirmButtonTheme("error primary");
        confirmDialog.addConfirmListener(event -> performDelete(beanToDelete));
        confirmDialog.open();
    }

    private void performDelete(B beanToDelete) {
        if (beanToDelete == null) {
            return;
        }

        boolean success = executeOperation(deleteOperation, beanToDelete,
                "Delete operation is not set. Cannot delete bean.");

        if (!success) {
            return;
        }

        // Refresh the list to show updated data
        crudList.refreshAllItems();

        if (deleteSuccessCallback != null) {
            deleteSuccessCallback.accept(beanToDelete);
        }

        // Hide form and deselect
        hideForm();
    }

    private boolean executeOperation(Consumer<B> operation, B bean, String missingOperationMessage) {
        if (operation == null) {
            return handleOperationError(new IllegalStateException(missingOperationMessage));
        }

        try {
            operation.accept(bean);
            return true;
        } catch (RuntimeException error) {
            return handleOperationError(error);
        }
    }

    private boolean handleOperationError(RuntimeException error) {
        if (operationErrorCallback != null) {
            operationErrorCallback.accept(error);
            return false;
        }

        throw error;
    }

    private void onUpdateClicked() {
        if (!updateOperationVisible) {
            return;
        }

        // Switch form from read-only to edit mode
        if (selectedBean != null) {
            showForm(selectedBean, CrudOperation.UPDATE);
        }
    }

    private void hideForm() {
        selectedBean = null;
        isCreating = false;
        clearListSelectionWithoutEvents();
        crudLayout.hideForm();
    }

    private void clearListSelectionWithoutEvents() {
        suppressSelectionEvents = true;
        try {
            crudList.clearSelection();
        } finally {
            suppressSelectionEvents = false;
        }
    }

    private void initializeDefaultButtonConfigs() {
        crudButtonConfigs.put(CrudOperation.CREATE, ButtonConfig.of("", VaadinIcon.PLUS::create, List.of()));
        crudButtonConfigs.put(CrudOperation.UPDATE, ButtonConfig.of("", VaadinIcon.EDIT::create, List.of(ButtonVariant.LUMO_PRIMARY)));
        crudButtonConfigs.put(CrudOperation.DELETE, ButtonConfig.of("", VaadinIcon.TRASH::create, List.of(ButtonVariant.LUMO_ERROR)));
        formButtonConfigs.put(CrudOperation.CREATE, ButtonConfig.of("Save", VaadinIcon.CHECK::create, List.of(ButtonVariant.LUMO_PRIMARY)));
        formButtonConfigs.put(CrudOperation.UPDATE, ButtonConfig.of("Save", VaadinIcon.CHECK::create, List.of(ButtonVariant.LUMO_PRIMARY)));
        formButtonConfigs.put(CrudOperation.READ, ButtonConfig.of("Cancel", null, List.of()));
    }

    private void applyCrudButtonConfig(Button button, CrudOperation operation) {
        if (button == null) {
            return;
        }

        ButtonConfig config = crudButtonConfigs.get(operation);
        button.setText(config.text);
        button.setIcon(config.createIcon());
        button.removeThemeVariants(ButtonVariant.values());
        if (!config.variants.isEmpty()) {
            button.addThemeVariants(config.variants.toArray(ButtonVariant[]::new));
        }
    }

    private void applyCrudButtonConfigIfPresent(CrudOperation operation) {
        switch (operation) {
            case CREATE -> applyCrudButtonConfig(createButton, operation);
            case UPDATE -> applyCrudButtonConfig(updateButton, operation);
            case DELETE -> applyCrudButtonConfig(deleteButton, operation);
            default -> {
            }
        }
    }

    private void applyFormButtonConfig(Button button, CrudOperation operation) {
        if (button == null) {
            return;
        }

        ButtonConfig config = formButtonConfigs.get(operation);
        button.setText(config.text);
        button.setIcon(config.createIcon());
        button.removeThemeVariants(ButtonVariant.values());
        if (!config.variants.isEmpty()) {
            button.addThemeVariants(config.variants.toArray(ButtonVariant[]::new));
        }
    }

    private void applyFormButtonConfigIfPresent(CrudOperation operation) {
        switch (operation) {
            case CREATE -> {
                if (isCreating) {
                    applyFormButtonConfig(saveButton, operation);
                }
            }
            case UPDATE -> {
                if (!isCreating) {
                    applyFormButtonConfig(saveButton, operation);
                }
            }
            case READ -> applyFormButtonConfig(cancelButton, operation);
            default -> {
            }
        }
    }

    private void applyOperationVisibility() {
        if (createButton != null) {
            createButton.setVisible(createOperationVisible);
        }

        if (deleteButton != null) {
            deleteButton.setVisible(deleteOperationVisible);
            if (!deleteOperationVisible) {
                deleteButton.setEnabled(false);
            }
        }

        if (updateButton != null) {
            updateButton.setVisible(updateOperationVisible);
            if (!updateOperationVisible) {
                updateButton.setEnabled(false);
            }
        }
    }

    private static class ButtonConfig {
        private String text;
        private Supplier<Component> iconSupplier;
        private List<ButtonVariant> variants;

        private static ButtonConfig of(String text, Supplier<Component> iconSupplier, List<ButtonVariant> variants) {
            ButtonConfig config = new ButtonConfig();
            config.text = text;
            config.iconSupplier = iconSupplier;
            config.variants = variants;
            return config;
        }

        private Component createIcon() {
            if (iconSupplier == null) {
                return null;
            }
            return iconSupplier.get();
        }
    }

    /**
     * Builder for configuring delete confirmation dialog settings in a fluent API.
     */
    public class DeleteConfirmationBuilder {
        /**
         * Sets all the text strings shown in the delete confirmation dialog.
         *
         * @param header Dialog header
         * @param message Dialog message
         * @param confirmText Confirm button text
         * @param cancelText Cancel button text
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> texts(String header, String message, String confirmText, String cancelText) {
            Crud.this.deleteConfirmationHeader = header;
            Crud.this.deleteConfirmationText = message;
            Crud.this.deleteConfirmationConfirmText = confirmText;
            Crud.this.deleteConfirmationCancelText = cancelText;
            return Crud.this;
        }

        /**
         * Sets the delete confirmation dialog header.
         *
         * @param header The dialog header text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder header(String header) {
            Crud.this.deleteConfirmationHeader = header;
            return this;
        }

        /**
         * Sets the delete confirmation dialog message.
         *
         * @param message The dialog message text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder message(String message) {
            Crud.this.deleteConfirmationText = message;
            return this;
        }

        /**
         * Sets the delete confirmation dialog confirm button text.
         *
         * @param confirmText The confirm button text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder confirmText(String confirmText) {
            Crud.this.deleteConfirmationConfirmText = confirmText;
            return this;
        }

        /**
         * Sets the delete confirmation dialog cancel button text.
         *
         * @param cancelText The cancel button text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder cancelText(String cancelText) {
            Crud.this.deleteConfirmationCancelText = cancelText;
            return this;
        }
    }

    /**
     * Builder for configuring individual action buttons in a fluent API.
     */
    public class ButtonBuilder {
        private final CrudOperation operation;

        ButtonBuilder(CrudOperation operation) {
            this.operation = operation;
        }

        /**
         * Sets the button label and icon.
         *
         * @param text The button label
         * @param icon The button icon component, or null for no icon
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text, Component icon, ButtonVariant... variants) {
            return label(text, icon == null ? null : () -> icon, variants);
        }

        /**
         * Sets the button label and icon.
         *
         * @param text The button label
         * @param iconSupplier Supplies the button icon component, or null for no icon
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text, Supplier<Component> iconSupplier, ButtonVariant... variants) {
            Crud.this.updateButtonConfig(Crud.this.crudButtonConfigs.get(operation), text, iconSupplier, variants);
            Crud.this.updateButtonConfig(Crud.this.formButtonConfigs.get(operation), text, iconSupplier, variants);
            Crud.this.applyCrudButtonConfigIfPresent(operation);
            Crud.this.applyFormButtonConfigIfPresent(operation);
            return Crud.this;
        }

        /**
         * Sets the button label only.
         *
         * @param text The button label
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text) {
            return label(text, (Supplier<Component>) null);
        }

        /**
         * Sets the button icon only.
         *
         * @param icon The button icon component
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> icon(Component icon) {
            return icon(() -> icon);
        }

        /**
         * Sets the button icon only.
         *
         * @param iconSupplier Supplies the button icon component
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> icon(Supplier<Component> iconSupplier) {
            Crud.this.updateButtonIcon(Crud.this.crudButtonConfigs.get(operation), iconSupplier);
            Crud.this.updateButtonIcon(Crud.this.formButtonConfigs.get(operation), iconSupplier);
            Crud.this.applyCrudButtonConfigIfPresent(operation);
            Crud.this.applyFormButtonConfigIfPresent(operation);
            return Crud.this;
        }

        /**
         * Sets the button variants (styling).
         *
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> variants(ButtonVariant... variants) {
            Crud.this.updateButtonVariants(Crud.this.crudButtonConfigs.get(operation), variants);
            Crud.this.updateButtonVariants(Crud.this.formButtonConfigs.get(operation), variants);
            Crud.this.applyCrudButtonConfigIfPresent(operation);
            Crud.this.applyFormButtonConfigIfPresent(operation);
            return Crud.this;
        }
    }

    private void updateButtonConfig(ButtonConfig config, String text, Supplier<Component> iconSupplier, ButtonVariant... variants) {
        if (config == null) {
            return;
        }
        config.text = text;
        config.iconSupplier = iconSupplier;
        config.variants = variants == null ? List.of() : Arrays.asList(variants);
    }

    private void updateButtonIcon(ButtonConfig config, Supplier<Component> iconSupplier) {
        if (config == null) {
            return;
        }
        config.iconSupplier = iconSupplier;
    }

    private void updateButtonVariants(ButtonConfig config, ButtonVariant... variants) {
        if (config == null) {
            return;
        }
        config.variants = variants == null ? List.of() : Arrays.asList(variants);
    }

}
