package org.vaadin.crudui2;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.provider.DataProvider;
import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.layout.CrudLayout;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;
import org.vaadin.crudui2.list.CrudList;
import org.vaadin.crudui2.list.impl.GridList;

/**
 * A fluent CRUD component factory. Creates a fully functional CRUD UI from a Java bean class
 * with sensible defaults: GridList + SplitCrudLayout + AutoGeneratedFormFactory.
 *
 * Usage:
 * <pre>
 * Crud&lt;User&gt; crud = Crud.of(User.class)
 *     .setDataProvider(dataProvider)
 *     .setCrudListener(listener)
 *     .build();
 * </pre>
 *
 * @param <B> The bean type
 */
public class Crud<B> extends Composite<VerticalLayout> {

    private final Class<B> beanType;
    private CrudList<B> crudList;
    private CrudLayout<B> crudLayout;
    private AutoGeneratedFormFactory<B> formFactory;
    private CrudForm<B> form;
    private CrudListener<B> crudListener;
    private B selectedBean;
    private boolean isCreating;
    private boolean built = false;
    private Button saveButton;
    private Button cancelButton;

    private Crud(Class<B> beanType) {
        this.beanType = beanType;
        this.isCreating = false;

        // Initialize the root VerticalLayout
        getContent().setSizeFull();
        getContent().setPadding(false);
    }

    /**
     * Creates a new Crud instance for the specified bean class.
     *
     * @param beanType The Java bean class
     * @param <B>      The bean type
     * @return A new Crud instance with default components
     */
    public static <B> Crud<B> of(Class<B> beanType) {
        Crud<B> crud = new Crud<>(beanType);
        crud.initializeDefaults();
        return crud;
    }

    private void initializeDefaults() {
        // Create default Grid with auto-detected columns
        Grid<B> grid = new Grid<>(beanType, true);

        // Wrap in GridList
        this.crudList = new GridList<>(grid);

        // Create default layout
        this.crudLayout = new SplitCrudLayout<>();
        this.crudLayout.setCrudList(crudList);

        // Create default form factory
        this.formFactory = AutoGeneratedFormFactory.of(beanType).useBeanValidation();

        // Add the layout to the root content
        getContent().add((Component) crudLayout);
    }

    /**
     * Sets the data provider for the list.
     *
     * @param dataProvider The data provider
     * @return This Crud instance for chaining
     */
    public Crud<B> setDataProvider(DataProvider<B, Void> dataProvider) {
        this.crudList.setDataProvider(dataProvider);
        return this;
    }

    /**
     * Sets the CRUD listener for backend operations.
     *
     * @param crudListener The listener
     * @return This Crud instance for chaining
     */
    public Crud<B> setCrudListener(CrudListener<B> crudListener) {
        this.crudListener = crudListener;
        return this;
    }

    /**
     * Overrides the default list implementation.
     *
     * @param crudList The custom list
     * @return This Crud instance for chaining
     */
    public Crud<B> setCrudList(CrudList<B> crudList) {
        this.crudList = crudList;
        this.crudLayout.setCrudList(crudList);
        return this;
    }

    /**
     * Overrides the default layout implementation.
     *
     * @param crudLayout The custom layout
     * @return This Crud instance for chaining
     */
    public Crud<B> setCrudLayout(CrudLayout<B> crudLayout) {
        this.crudLayout = crudLayout;
        return this;
    }

    /**
     * Overrides the default form factory.
     *
     * @param formFactory The custom form factory
     * @return This Crud instance for chaining
     */
    public Crud<B> setCrudFormFactory(AutoGeneratedFormFactory<B> formFactory) {
        this.formFactory = formFactory;
        return this;
    }

    /**
     * Gets the current CRUD listener, if set.
     *
     * @return The listener or null if not set
     */
    public CrudListener<B> getCrudListener() {
        return crudListener;
    }

    /**
     * Gets the current CrudList implementation.
     *
     * @return The list
     */
    public CrudList<B> getCrudList() {
        return crudList;
    }

    /**
     * Gets the current CrudLayout implementation.
     *
     * @return The layout
     */
    public CrudLayout<B> getCrudLayout() {
        return crudLayout;
    }

    /**
     * Gets the current form factory.
     *
     * @return The form factory
     */
    public AutoGeneratedFormFactory<B> getCrudFormFactory() {
        return formFactory;
    }

    /**
     * Builds and returns the CRUD component ready to be added to a layout.
     * Wires up all listeners and interactions.
     *
     * @return This Crud instance as a Vaadin Component
     */
    public Crud<B> build() {
        if (built) {
            return this;
        }
        built = true;

        // Wire item selection listener
        crudList.addItemSelectedListener(bean -> {
            if (bean != null) {
                selectedBean = bean;
                isCreating = false;
                showForm(bean);
            } else {
                hideForm();
            }
        });

        // Create "Create" button
        Button createButton = new Button("Create", e -> {
            try {
                selectedBean = beanType.getDeclaredConstructor().newInstance();
                isCreating = true;
                showForm(selectedBean);
            } catch (Exception ex) {
                throw new RuntimeException("Failed to create new instance of " + beanType.getName(), ex);
            }
        });

        // Add Create button to layout
        crudLayout.addCrudActionComponent(createButton);

        return this;
    }

    private void showForm(B bean) {
        // Update the form
        form = formFactory.build(bean);

        // Lazy-create buttons on first use (they're reused across form displays)
        if (saveButton == null) {
            saveButton = new Button("Save", e -> onSaveClicked());
            saveButton.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
            cancelButton = new Button("Cancel", e -> hideForm());
        }

        // Show form and add action buttons
        crudLayout.showCrudForm(form);
        crudLayout.addFormActionComponent(saveButton);
        crudLayout.addFormActionComponent(cancelButton);
    }

    private void onSaveClicked() {
        if (!form.isValid()) {
            return;
        }

        B savedBean = form.getValue();

        if (crudListener == null) {
            throw new IllegalStateException(
                "CrudListener not set. Cannot save bean. Call setCrudListener() to enable save operations.");
        }

        if (isCreating) {
            crudListener.onCreate(savedBean);
            isCreating = false;
        } else {
            crudListener.onSave(savedBean);
        }

        // Refresh the list to show updated data
        crudList.refreshAllItems();

        // Hide form after save
        hideForm();
    }

    private void hideForm() {
        selectedBean = null;
        isCreating = false;
        crudLayout.hideForm();
    }

}
