package org.vaadin.crudui2;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.provider.DataProvider;
import org.vaadin.crudui2.data.provider.SimpleBackendDataProvider;
import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.CrudFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.layout.CrudLayout;
import org.vaadin.crudui2.layout.CrudLayoutFactory;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;
import org.vaadin.crudui2.list.CrudList;
import org.vaadin.crudui2.list.CrudListFactory;
import org.vaadin.crudui2.list.impl.GridList;

import java.util.Arrays;
import java.util.EnumMap;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * A fluent CRUD component factory. Creates a fully functional CRUD UI from a Java bean class
 * with sensible defaults: GridList + SplitCrudLayout + AutoGeneratedFormFactory.
 *
 * Usage with lambda methods:
 * <pre>
 * Crud&lt;User&gt; crud = Crud.of(User.class)
 *     .onRead(userService::findAll)
 *     .onCreate(userService::save)
 *     .onUpdate(userService::save)
 *     .onDelete(userService::delete)
 *     .build();
 * </pre>
 *
 * Usage with CrudListener implementation:
 * <pre>
 * Crud&lt;User&gt; crud = Crud.of(User.class)
 *     .crudListener(this)
 *     .build();
 * </pre>
 *
 * @param <B> The bean type
 */
public class Crud<B> extends Composite<VerticalLayout> {

    private final Class<B> beanType;
    private CrudList<B> crudList;
    private CrudLayout<B> crudLayout;
    private CrudFormFactory<B> formFactory;
    private CrudForm<B> form;
    private CrudListener<B> crudListener;
    private Supplier<List<B>> readOperation;
    private Consumer<B> createOperation;
    private Consumer<B> updateOperation;
    private Consumer<B> deleteOperation;
    private B selectedBean;
    private boolean isCreating;
    private boolean built = false;
    private Button createButton;
    private Button deleteButton;
    private Button saveButton;
    private Button cancelButton;
    private Button updateButton;
    private boolean viewBeforeEdit = false;
    private boolean createOperationVisible = true;
    private boolean updateOperationVisible = true;
    private boolean deleteOperationVisible = true;
    private boolean suppressSelectionEvents = false;
    private final EnumMap<CrudAction, ButtonConfig> buttonConfigs = new EnumMap<>(CrudAction.class);
    private String deleteConfirmationHeader = "Delete item?";
    private String deleteConfirmationText = "Are you sure you want to delete this item?";
    private String deleteConfirmationConfirmText = "Delete";
    private String deleteConfirmationCancelText = "Cancel";


    private Crud(Class<B> beanType) {
        this.beanType = beanType;
        this.isCreating = false;

        // Initialize the root VerticalLayout
        getContent().setSizeFull();
        getContent().setPadding(false);

        initializeDefaultButtonConfigs();
    }

    /**
     * Creates a new Crud instance for the specified bean class.
     *
     * @param beanType The Java bean class
     * @param <B>      The bean type
     * @return A new Crud instance with default components
     */
    public static <B> Crud<B> of(Class<B> beanType) {
        Crud<B> crud = new Crud<>(beanType);
        crud.initializeDefaults();
        return crud;
    }

    private void initializeDefaults() {
        // Create default Grid with auto-detected columns
        Grid<B> grid = new Grid<>(beanType, true);

        // Wrap in GridList using fluent builder
        this.crudList = GridList.of(beanType).grid(grid).build();

        // Create default layout using fluent builder
        this.crudLayout = SplitCrudLayout.of(beanType).build();
        this.crudLayout.setCrudList(crudList);

        // Create default form factory
        this.formFactory = AutoGeneratedFormFactory.of(beanType).useBeanValidation();

        // Add the layout to the root content
        getContent().add((Component) crudLayout);
    }

    /**
     * Sets the data provider for the list.
     *
     * @param dataProvider The data provider
     * @return This Crud instance for chaining
     */
    public Crud<B> dataProvider(DataProvider<B, Void> dataProvider) {
        this.crudList.setDataProvider(dataProvider);
        return this;
    }

    /**
     * Sets the CRUD listener for backend operations (using interface approach).
     *
     * @param crudListener The listener
     * @return This Crud instance for chaining
     */
    public Crud<B> crudListener(CrudListener<B> crudListener) {
        this.crudListener = crudListener;
        return this;
    }

    /**
     * Sets the read operation (lambda approach).
     *
     * @param readOperation A supplier that returns the list of beans
     * @return This Crud instance for chaining
     */
    public Crud<B> onRead(Supplier<List<B>> readOperation) {
        this.readOperation = readOperation;
        return this;
    }

    /**
     * Sets the create operation (lambda approach).
     *
     * @param createOperation A consumer that saves the new bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onCreate(Consumer<B> createOperation) {
        this.createOperation = createOperation;
        return this;
    }

    /**
     * Sets the update operation (lambda approach).
     *
     * @param updateOperation A consumer that updates the bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onUpdate(Consumer<B> updateOperation) {
        this.updateOperation = updateOperation;
        return this;
    }

    /**
     * Sets the delete operation (lambda approach).
     *
     * @param deleteOperation A consumer that deletes the bean
     * @return This Crud instance for chaining
     */
    public Crud<B> onDelete(Consumer<B> deleteOperation) {
        this.deleteOperation = deleteOperation;
        return this;
    }

    /**
     * Enables or disables the view-before-edit mode.
     * When enabled, forms are shown in read-only mode with an "Update" button to enable editing.
     * When disabled (default), forms are shown in editable mode immediately.
     *
     * @param viewBeforeEdit true to show read-only forms first, false for immediate edit mode
     * @return This Crud instance for chaining
     */
    public Crud<B> viewBeforeEdit(boolean viewBeforeEdit) {
        this.viewBeforeEdit = viewBeforeEdit;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the create operation is visible.
     *
     * @param visible true to show create operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> createOperationVisible(boolean visible) {
        this.createOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the update operation is visible.
     *
     * @param visible true to show update operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> updateOperationVisible(boolean visible) {
        this.updateOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Controls whether the delete operation is visible.
     *
     * @param visible true to show delete operation, false to hide it
     * @return This Crud instance for chaining
     */
    public Crud<B> deleteOperationVisible(boolean visible) {
        this.deleteOperationVisible = visible;
        applyOperationVisibility();
        return this;
    }

    /**
     * Sets the form factory.
     *
     * @param factory The form factory to use
     * @return This Crud instance for chaining
     */
    public Crud<B> form(CrudFormFactory<B> factory) {
        this.formFactory = factory;
        return this;
    }

    /**
     * Returns a builder for configuring delete confirmation dialog settings.
     *
     * @return A DeleteConfirmationBuilder for chaining delete confirmation configuration
     */
    public DeleteConfirmationBuilder deleteConfirmation() {
        return new DeleteConfirmationBuilder();
    }

    /**
     * Returns a builder for configuring a specific action button.
     *
     * @param action The action button to configure
     * @return A ButtonBuilder for chaining button configuration
     */
    public ButtonBuilder button(CrudAction action) {
        return new ButtonBuilder(action);
    }

    /**
     * Sets the list implementation using a factory.
     *
     * @param listFactory The list factory
     * @return This Crud instance for chaining
     */
    public Crud<B> list(CrudListFactory<B> listFactory) {
        this.crudList = listFactory.build();
        this.crudLayout.setCrudList(this.crudList);
        applyOperationVisibility();
        return this;
    }

    /**
     * Overrides the default layout implementation using a factory.
     *
     * @param layoutFactory The layout factory
     * @return This Crud instance for chaining
     */
    public Crud<B> layout(CrudLayoutFactory<B> layoutFactory) {
        // Remove old layout from root if it exists
        if (this.crudLayout != null) {
            getContent().remove((Component) this.crudLayout);
        }

        // Build the new layout
        this.crudLayout = layoutFactory.build();

        // Set the current crudList on the new layout
        this.crudLayout.setCrudList(this.crudList);

        // Add the new layout to the root
        getContent().add((Component) this.crudLayout);

        return this;
    }



    /**
     * Builds and returns the CRUD component ready to be added to a layout.
     * Wires up all listeners and interactions.
     *
     * @return This Crud instance as a Vaadin Component
     */
    public Crud<B> build() {
        if (built) {
            return this;
        }
        built = true;

        // Set up the data provider based on either listener or lambda methods
        setupDataProvider();

        // Create action buttons before selection listeners so enable state can be updated consistently
        createButton = new Button("Create", e -> {
            try {
                // Entering create mode must clear list selection and disable update/delete actions.
                if (deleteButton != null) {
                    deleteButton.setEnabled(false);
                }
                if (updateButton != null) {
                    updateButton.setEnabled(false);
                }

                clearListSelectionWithoutEvents();

                selectedBean = beanType.getDeclaredConstructor().newInstance();
                isCreating = true;
                showForm(selectedBean);
            } catch (Exception ex) {
                suppressSelectionEvents = false;
                throw new RuntimeException("Failed to create new instance of " + beanType.getName(), ex);
            }
        });

        deleteButton = new Button("Delete", e -> onDeleteClicked());
        deleteButton.setEnabled(false);

        applyButtonConfig(createButton, CrudAction.CREATE);
        applyButtonConfig(deleteButton, CrudAction.DELETE);

        // Create "Update" button for read-only form mode (only if viewBeforeEdit is enabled)
        if (viewBeforeEdit) {
            updateButton = new Button("Update", e -> onUpdateClicked());
            updateButton.setEnabled(false);
            applyButtonConfig(updateButton, CrudAction.UPDATE);
        }

        // Wire item selection listener
        crudList.addItemSelectedListener(bean -> {
            if (suppressSelectionEvents) {
                return;
            }

            if (bean != null) {
                selectedBean = bean;
                isCreating = false;
                if (deleteOperationVisible) {
                    deleteButton.setEnabled(true);
                }
                if (viewBeforeEdit && updateButton != null && updateOperationVisible) {
                    updateButton.setEnabled(true);
                }
                showForm(bean);
            } else {
                deleteButton.setEnabled(false);
                if (viewBeforeEdit && updateButton != null) {
                    updateButton.setEnabled(false);
                }
                hideForm();
            }
        });

        // Add Create, Update (if enabled), and Delete buttons to layout in order
        crudLayout.addCrudActionComponent(createButton);

        // Add Update button to layout if viewBeforeEdit is enabled
        if (viewBeforeEdit && updateButton != null) {
            crudLayout.addCrudActionComponent(updateButton);
        }

        crudLayout.addCrudActionComponent(deleteButton);
        applyOperationVisibility();

        return this;
    }

    private void setupDataProvider() {
        // Check if we have either lambda methods or a listener
        if (readOperation != null) {
            // Use lambda method approach
            crudList.setDataProvider(
                new SimpleBackendDataProvider<B>(readOperation::get)
            );
        } else if (crudListener != null) {
            // Use listener approach
            crudList.setDataProvider(
                new SimpleBackendDataProvider<B>(() -> crudListener.onRead())
            );
        }
        // If neither is set, the data provider will be empty (no-op) until configured
    }

    private void showForm(B bean) {
        // Update the form
        form = formFactory.build(bean);

        // Lazy-create buttons on first use (they're reused across form displays)
        if (saveButton == null) {
            saveButton = new Button("Save", e -> onSaveClicked());
            cancelButton = new Button("Cancel", e -> hideForm());
            applyButtonConfig(saveButton, CrudAction.SAVE);
            applyButtonConfig(cancelButton, CrudAction.CANCEL);
        }

        // Determine if form should be read-only
        boolean shouldBeReadOnly = !isCreating && (viewBeforeEdit || !updateOperationVisible);
        form.setReadOnly(shouldBeReadOnly);

        // Show form and add action buttons
        crudLayout.showCrudForm(form);
        crudLayout.setFormActionCaption(shouldBeReadOnly ? null : (isCreating ? formFactory.getCreateCaption() : formFactory.getUpdateCaption()));

        if (shouldBeReadOnly) {
            // Show only Cancel button in read-only mode (Update button is in layout)
            crudLayout.addFormActionComponent(cancelButton);
        } else {
            // Show Save/Cancel buttons in edit mode
            crudLayout.addFormActionComponent(saveButton);
            crudLayout.addFormActionComponent(cancelButton);
        }
    }

    private void onSaveClicked() {
        if (!form.isValid()) {
            return;
        }

        B savedBean = form.getValue();

        if (isCreating) {
            // Handle create
            if (createOperation != null) {
                createOperation.accept(savedBean);
            } else if (crudListener != null) {
                crudListener.onCreate(savedBean);
            } else {
                throw new IllegalStateException(
                    "Neither create operation nor CrudListener is set. Cannot create bean.");
            }
        } else {
            // Handle update
            if (updateOperation != null) {
                updateOperation.accept(savedBean);
            } else if (crudListener != null) {
                crudListener.onUpdate(savedBean);
            } else {
                throw new IllegalStateException(
                    "Neither update operation nor CrudListener is set. Cannot update bean.");
            }
        }

        isCreating = false;

        // Refresh the list to show updated data
        crudList.refreshAllItems();

        // Hide form after save
        hideForm();
    }

    private void onDeleteClicked() {
        if (selectedBean == null) {
            return;
        }

        B beanToDelete = selectedBean;
        ConfirmDialog confirmDialog = new ConfirmDialog();
        confirmDialog.setHeader(deleteConfirmationHeader);
        confirmDialog.setText(deleteConfirmationText);
        confirmDialog.setCancelable(true);
        confirmDialog.setCancelText(deleteConfirmationCancelText);
        confirmDialog.setConfirmText(deleteConfirmationConfirmText);
        confirmDialog.setConfirmButtonTheme("error primary");
        confirmDialog.addConfirmListener(event -> performDelete(beanToDelete));
        confirmDialog.open();
    }

    private void performDelete(B beanToDelete) {
        if (beanToDelete == null) {
            return;
        }

        if (deleteOperation != null) {
            deleteOperation.accept(beanToDelete);
        } else if (crudListener != null) {
            crudListener.onDelete(beanToDelete);
        } else {
            throw new IllegalStateException(
                "Neither delete operation nor CrudListener is set. Cannot delete bean.");
        }

        // Refresh the list to show updated data
        crudList.refreshAllItems();

        // Hide form and deselect
        hideForm();
    }

    private void onUpdateClicked() {
        if (!updateOperationVisible) {
            return;
        }

        // Switch form from read-only to edit mode
        if (form != null) {
            form.setReadOnly(false);

            // Update form actions to show Save/Cancel instead of just Cancel
            crudLayout.hideForm();
            crudLayout.showCrudForm(form);
            crudLayout.setFormActionCaption(formFactory.getUpdateCaption());
            crudLayout.addFormActionComponent(saveButton);
            crudLayout.addFormActionComponent(cancelButton);
        }
    }

    private void hideForm() {
        selectedBean = null;
        isCreating = false;
        clearListSelectionWithoutEvents();
        crudLayout.hideForm();
    }

    private void clearListSelectionWithoutEvents() {
        suppressSelectionEvents = true;
        try {
            crudList.clearSelection();
        } finally {
            suppressSelectionEvents = false;
        }
    }

    private void initializeDefaultButtonConfigs() {
        buttonConfigs.put(CrudAction.CREATE, ButtonConfig.of("", VaadinIcon.PLUS::create, List.of()));
        buttonConfigs.put(CrudAction.UPDATE, ButtonConfig.of("", VaadinIcon.EDIT::create, List.of(ButtonVariant.LUMO_PRIMARY)));
        buttonConfigs.put(CrudAction.DELETE, ButtonConfig.of("", VaadinIcon.TRASH::create, List.of(ButtonVariant.LUMO_ERROR)));
        buttonConfigs.put(CrudAction.SAVE, ButtonConfig.of("Save", VaadinIcon.CHECK::create, List.of(ButtonVariant.LUMO_PRIMARY)));
        buttonConfigs.put(CrudAction.CANCEL, ButtonConfig.of("Cancel", null, List.of()));
    }

    private void applyButtonConfig(Button button, CrudAction action) {
        if (button == null) {
            return;
        }

        ButtonConfig config = buttonConfigs.get(action);
        button.setText(config.text);
        button.setIcon(config.createIcon());
        button.removeThemeVariants(ButtonVariant.values());
        if (!config.variants.isEmpty()) {
            button.addThemeVariants(config.variants.toArray(ButtonVariant[]::new));
        }
    }

    private void applyButtonConfigIfPresent(CrudAction action) {
        switch (action) {
            case CREATE -> applyButtonConfig(createButton, action);
            case UPDATE -> applyButtonConfig(updateButton, action);
            case DELETE -> applyButtonConfig(deleteButton, action);
            case SAVE -> applyButtonConfig(saveButton, action);
            case CANCEL -> applyButtonConfig(cancelButton, action);
            default -> {
            }
        }
    }

    private void applyOperationVisibility() {
        if (createButton != null) {
            createButton.setVisible(createOperationVisible);
        }

        if (deleteButton != null) {
            deleteButton.setVisible(deleteOperationVisible);
            if (!deleteOperationVisible) {
                deleteButton.setEnabled(false);
            }
        }

        if (updateButton != null) {
            updateButton.setVisible(viewBeforeEdit && updateOperationVisible);
            if (!updateOperationVisible) {
                updateButton.setEnabled(false);
            }
        }
    }

    private static class ButtonConfig {
        private String text;
        private Supplier<Component> iconSupplier;
        private List<ButtonVariant> variants;

        private static ButtonConfig of(String text, Supplier<Component> iconSupplier, List<ButtonVariant> variants) {
            ButtonConfig config = new ButtonConfig();
            config.text = text;
            config.iconSupplier = iconSupplier;
            config.variants = variants;
            return config;
        }

        private Component createIcon() {
            if (iconSupplier == null) {
                return null;
            }
            return iconSupplier.get();
        }
    }

    /**
     * Builder for configuring delete confirmation dialog settings in a fluent API.
     */
    public class DeleteConfirmationBuilder {
        /**
         * Sets all the text strings shown in the delete confirmation dialog.
         *
         * @param header Dialog header
         * @param message Dialog message
         * @param confirmText Confirm button text
         * @param cancelText Cancel button text
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> texts(String header, String message, String confirmText, String cancelText) {
            Crud.this.deleteConfirmationHeader = header;
            Crud.this.deleteConfirmationText = message;
            Crud.this.deleteConfirmationConfirmText = confirmText;
            Crud.this.deleteConfirmationCancelText = cancelText;
            return Crud.this;
        }

        /**
         * Sets the delete confirmation dialog header.
         *
         * @param header The dialog header text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder header(String header) {
            Crud.this.deleteConfirmationHeader = header;
            return this;
        }

        /**
         * Sets the delete confirmation dialog message.
         *
         * @param message The dialog message text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder message(String message) {
            Crud.this.deleteConfirmationText = message;
            return this;
        }

        /**
         * Sets the delete confirmation dialog confirm button text.
         *
         * @param confirmText The confirm button text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder confirmText(String confirmText) {
            Crud.this.deleteConfirmationConfirmText = confirmText;
            return this;
        }

        /**
         * Sets the delete confirmation dialog cancel button text.
         *
         * @param cancelText The cancel button text
         * @return This DeleteConfirmationBuilder for continuing configuration
         */
        public DeleteConfirmationBuilder cancelText(String cancelText) {
            Crud.this.deleteConfirmationCancelText = cancelText;
            return this;
        }
    }

    /**
     * Builder for configuring individual action buttons in a fluent API.
     */
    public class ButtonBuilder {
        private final CrudAction action;

        ButtonBuilder(CrudAction action) {
            this.action = action;
        }

        /**
         * Sets the button label and icon.
         *
         * @param text The button label
         * @param icon The button icon component, or null for no icon
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text, Component icon, ButtonVariant... variants) {
            return label(text, icon == null ? null : () -> icon, variants);
        }

        /**
         * Sets the button label and icon.
         *
         * @param text The button label
         * @param iconSupplier Supplies the button icon component, or null for no icon
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text, Supplier<Component> iconSupplier, ButtonVariant... variants) {
            ButtonConfig config = Crud.this.buttonConfigs.get(action);
            config.text = text;
            config.iconSupplier = iconSupplier;
            config.variants = variants == null ? List.of() : Arrays.asList(variants);
            Crud.this.applyButtonConfigIfPresent(action);
            return Crud.this;
        }

        /**
         * Sets the button label only.
         *
         * @param text The button label
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> label(String text) {
            return label(text, (Supplier<Component>) null);
        }

        /**
         * Sets the button icon only.
         *
         * @param icon The button icon component
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> icon(Component icon) {
            return icon(() -> icon);
        }

        /**
         * Sets the button icon only.
         *
         * @param iconSupplier Supplies the button icon component
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> icon(Supplier<Component> iconSupplier) {
            ButtonConfig config = Crud.this.buttonConfigs.get(action);
            config.iconSupplier = iconSupplier;
            Crud.this.applyButtonConfigIfPresent(action);
            return Crud.this;
        }

        /**
         * Sets the button variants (styling).
         *
         * @param variants The button variants to apply
         * @return This Crud instance for continuing the fluent chain
         */
        public Crud<B> variants(ButtonVariant... variants) {
            ButtonConfig config = Crud.this.buttonConfigs.get(action);
            config.variants = variants == null ? List.of() : Arrays.asList(variants);
            Crud.this.applyButtonConfigIfPresent(action);
            return Crud.this;
        }
    }

}
