package org.vaadin.crudui.demo.ui.view;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Set;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.HasValue;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.splitlayout.SplitLayout.Orientation;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.provider.DataProvider;
import com.vaadin.flow.data.provider.HasListDataView;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.Crud;
import org.vaadin.crudui.CrudOperation;
import org.vaadin.crudui.demo.entity.Group;
import org.vaadin.crudui.demo.entity.MaritalStatus;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui.demo.ui.MainLayout;
import org.vaadin.crudui.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui.form.impl.autogenerated.Field;
import org.vaadin.crudui.form.impl.autogenerated.field.provider.ComboBoxProvider;
import org.vaadin.crudui.form.impl.autogenerated.field.provider.MultiSelectComboBoxProvider;
import org.vaadin.crudui.layout.impl.SplitCrudLayout;
import org.vaadin.crudui.list.impl.GridList;

@Route(value = "customized", layout = MainLayout.class)
public class CustomizedView extends VerticalLayout {

	private UserService userService;

    private TextField nameFilter = new TextField();

	public CustomizedView(UserService userService, GroupService groupService) {
		this.userService = userService;

        var crud = Crud.of(User.class);

        nameFilter.setPlaceholder("Search by name...");
        nameFilter.setClearButtonVisible(true);
        nameFilter.setPrefixComponent(VaadinIcon.SEARCH.create());

        Grid<User> grid = new Grid<>();
        grid.addColumn(User::getName).setHeader("The name").setAutoWidth(true);
        grid.addColumn(User::getBirthDate).setHeader("The birth date");
        grid.addColumn(User::getMaritalStatus).setHeader("The marital status");
        grid.addColumn(User::getEmail).setHeader("The email").setAutoWidth(true);
        grid.addColumn(User::getPhoneNumber).setHeader("The phone number");
		grid.setColumnReorderingAllowed(true);
		grid.addComponentColumn(user -> {
            var button = new Button(VaadinIcon.TRASH.create(), event -> crud.clickDelete(user));
			button.addThemeVariants(ButtonVariant.LUMO_ERROR, ButtonVariant.LUMO_SMALL);
			return button;
		}).setFlexGrow(0);

        var mainGroupField = Field.of(User::getMainGroup, User::setMainGroup, Group.class);

        crud
                .layout(SplitCrudLayout.of(User.class)
                        .orientation(Orientation.HORIZONTAL))
                        .addFilterComponent(nameFilter)
                .list(GridList.of(User.class)
                        .grid(grid))
                .form(AutoGeneratedFormFactory.of(User.class)
                        .fields(
                                Field.of(User::getName, User::setName, String.class).label("The name").enabled(false),
                                Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("The birth date"),
                                Field.of(User::getEmail, User::setEmail, String.class).label("The email"),
                                Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("The salary"),
                                Field.of(User::getPhoneNumber, User::setPhoneNumber, Integer.class).label("The phone number"),
                                Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("The marital status"),
                                Field.of(User::getGroups, User::setGroups, Set.class).label("In groups")
                                        .fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName))
                                        .onValueChangeUpdate(mainGroupField),
                                mainGroupField.label("Main group")
                                        .fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName))
                                        .onUpdate(this::populateMainGroupBox),
                                Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
                        .fieldsFor(CrudOperation.CREATE,
                                Field.of(User::getName, User::setName, String.class).label("The name"),
                                Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("The birth date"),
                                Field.of(User::getEmail, User::setEmail, String.class).label("The email"),
                                Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("The salary"),
                                Field.of(User::getPhoneNumber, User::setPhoneNumber, Integer.class).label("The phone number"),
                                Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("The marital status"),
                                Field.of(User::getGroups, User::setGroups, Set.class).label("In groups")
                                        .fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName))
                                        .onValueChangeUpdate(mainGroupField),
                                mainGroupField.label("Main group")
                                        .fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName))
                                        .onUpdate(this::populateMainGroupBox),
                                Field.of(User::getPassword, User::setPassword, String.class).label("The password"),
                                Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
                        .useBeanValidation()
                        .captions("Create new User", "Edit User"))
                .viewBeforeEdit(true)
                .deleteOperationVisible(false)
                .onCreate(this::create)
                .onRead(getDataProvider())
                .onUpdate(this::update)
                .onDelete(this::delete)
                .build();

		// view configuration
		setSizeFull();
		add(crud);
	}

	public User create(User user) {
		return userService.save(user);
	}

	public DataProvider<User, Void> getDataProvider() {
		return DataProvider.fromCallbacks(
				query -> userService.findByNameContainingIgnoreCase(
						nameFilter.getValue(), query.getPage(), query.getPageSize()).stream(),
				query -> (int) userService.countByNameContainingIgnoreCase(nameFilter.getValue()));
	}

	public User update(User user) {
		if (user.getId().equals(1L)) {
			throw new RuntimeException("Simulated exception (only for user ID 1).");
		}
		return userService.save(user);
	}

	public void delete(User user) {
		userService.delete(user);
	}

    private void populateMainGroupBox(AbstractField<?, Group> field, Object bean) {
        var hasItems = (HasListDataView<Group, ?>) field;
        var hasValue = (HasValue<?, Group>) field;
        User user = (User) bean;
        Group previousMainGroup = user.getMainGroup();
        hasItems.setItems(user.getGroups());
        if (user.getGroups().contains(previousMainGroup)) {
            hasValue.setValue(previousMainGroup);
        }
    }

}
