package org.vaadin.crudui.demo.ui.view;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Set;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.HasValue;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.radiobutton.RadioButtonGroup;
import com.vaadin.flow.component.splitlayout.SplitLayout.Orientation;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.provider.DataProvider;
import com.vaadin.flow.data.provider.HasListDataView;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.Group;
import org.vaadin.crudui.demo.entity.MaritalStatus;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field;
import org.vaadin.crudui2.form.impl.autogenerated.field.provider.ComboBoxProvider;
import org.vaadin.crudui2.form.impl.autogenerated.field.provider.MultiSelectComboBoxProvider;
import org.vaadin.crudui2.form.impl.autogenerated.field.provider.RadioButtonGroupProvider;
import org.vaadin.crudui2.layout.CrudLayout;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;
import org.vaadin.crudui2.list.CrudList;
import org.vaadin.crudui2.list.impl.GridList;

@Route(value = "playground1")
@JsModule("theme-handler.js")
public class PlaygroundView1 extends VerticalLayout {

	public PlaygroundView1(UserService userService, GroupService groupService) {
		var mainGroupField = Field.of(User::getMainGroup, User::setMainGroup, Group.class);
		var mainGroupField2 = Field.of("mainGroup");

		// @formatter:off
		CrudForm<User> userForm = AutoGeneratedFormFactory.of(User.class)
				//*
				.setFields(
						Field.of(User::getName, User::setName, String.class).label("Name")
								.enabled(false),
						Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("Marital status"),
						Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("Birth date"),
						Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("Salary"),
						Field.of(User::getGroups, User::setGroups, Set.class).label("In groups")
								.fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName))
								.onValueChangeUpdate(mainGroupField),
						mainGroupField.label("Main group")
								.fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName))
								.onUpdate(this::populateMainGroupBox),
						Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
				//*/
				//*
				.add(Field.of(User::getName, User::setName, String.class).label("Name")
						.enabled(false))
				.add(Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("Marital status"))
				.add(Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("Birth date"))
				.add(Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("Salary"))
				.add(Field.of(User::getGroups, User::setGroups, Set.class).label("In groups")
						.fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName))
						.onValueChangeUpdate(mainGroupField))
				.add(mainGroupField.label("Main group")
						.fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName))
						.onUpdate(this::populateMainGroupBox))
				.add(Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
				//*/
				//**
				.setFields(
						Field.of("name").label("The name"),
						Field.of("birthDate").label("The date of birth"),
						Field.of("email").label("The email"),
						Field.of("salary").label("The salary"),
						Field.of("phoneNumber").label("The phone number"),
						Field.of("maritalStatus").label("The marital status")
								.fieldType(RadioButtonGroup.class),
						Field.of("groups").label("The groups")
								.fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName))
								.onValueChangeUpdate(mainGroupField2),
						mainGroupField2.label("The main group")
								.fieldProvider(new RadioButtonGroupProvider<>(User::getGroups, Group::getName))
								.onUpdate(this::populateMainGroupBox),
						Field.of("active").label("Is it active?"))
				// */
				.useBeanValidation()
				.build(new User());
		// @formatter:on

		var name = new TextField();
		name.setPlaceholder("Search by name...");
		name.setClearButtonVisible(true);
		name.setPrefixComponent(VaadinIcon.SEARCH.create());

		var grid = new Grid<User>();
		grid.addColumn(User::getId);
		grid.addColumn(User::getName).setHeader("The name of the user");
		grid.addColumn(User::getBirthDate).setHeader("The birth date of the user");
		//grid.getHeaderRows().get(0).getCells().get(0).setComponent(component);

		CrudList<User> userList = new GridList<>(grid);
		userList.setDataProvider(DataProvider.fromCallbacks(
				q -> userService.findByNameContainingIgnoreCase(name.getValue(), q.getPage(), q.getPageSize()).stream(),
				q -> (int) userService.countByNameContainingIgnoreCase(name.getValue())));

		CrudLayout<User> layout = new SplitCrudLayout<>(Orientation.HORIZONTAL); // check vertical
		layout.setCrudList(userList);
		layout.addFilterComponent(name);

		var save = new Button("Save", e -> {
			try {
				if (userForm.isValid()) {
					User user = userForm.getValue();
					boolean isNewUser = user.getId() == null;
					userService.save(user);
					if (isNewUser) {
						layout.getCrudList().refreshAllItems();
						Notification.show("User saved: " + user);
					} else {
						layout.getCrudList().refreshItem(user);
						Notification.show("User updated: " + user);
					}

				} else {
					Notification.show("Form not valid");
				}
			} catch (Exception ex) {
				Notification.show("Error: " + ex.getMessage());
				ex.printStackTrace();
				return;
			}
		});

		layout.getCrudList().addItemSelectedListener(user -> {
			if (user != null) {
				userForm.setValue(user);
				layout.showCrudForm(userForm);
				layout.addFormActionComponent(save);
			} else {
				layout.hideForm();
			}
		});

		var create = new Button("Create", e -> {
			userForm.setValue(new User());
			layout.showCrudForm(userForm);
			layout.addFormActionComponent(save);
		});

		layout.addCrudActionComponent(create);

		add((Component) layout);
		expand((Component) layout);
		setSizeFull();
		//setPadding(false);
		UI.getCurrent().getPage().executeJs("window.applySystemTheme()");
	}

	private void populateMainGroupBox(AbstractField<?, Group> field, Object bean) {
		var hasItems = (HasListDataView<Group, ?>) field;
		var hasValue = (HasValue<?, Group>) field;
		User user = (User) bean;
		Group previousMainGroup = user.getMainGroup();
		hasItems.setItems(user.getGroups());
		if (user.getGroups().contains(previousMainGroup)) {
			hasValue.setValue(previousMainGroup);
		}
	}

}
