package org.vaadin.crudui.demo.ui.view;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Set;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.HasValue;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.radiobutton.RadioButtonGroup;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.data.provider.HasListDataView;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.Group;
import org.vaadin.crudui.demo.entity.MaritalStatus;
import org.vaadin.crudui.demo.entity.Technology;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.TechnologyService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field;
import org.vaadin.crudui2.form.impl.autogenerated.provider.ComboBoxProvider;
import org.vaadin.crudui2.form.impl.autogenerated.provider.MultiSelectComboBoxProvider;
import org.vaadin.crudui2.form.impl.autogenerated.provider.RadioButtonGroupProvider;

@Route(value = "playground1")
@JsModule("theme-handler.js")
public class PlaygroundView1 extends HorizontalLayout {

	public PlaygroundView1(UserService userService, GroupService groupService, TechnologyService technologyService) {
		User user = userService.findByNameContainingIgnoreCase("Edgar", 1, 2).get().findFirst().orElse(null);

		var mainGroupField = Field.of(User::getMainGroup, User::setMainGroup, Group.class);
		var mainGroupField2 = Field.of("mainGroup");

		var userForm = AutoGeneratedFormFactory.of(User.class)
				//*
				.setFields(
						Field.of(User::getName, User::setName, String.class).label("Name").enabled(false),
						Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("Marital status"),
						Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("Birth date"),
						Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("Salary"),
						Field.of(User::getGroups, User::setGroups, Set.class).label("In groups").fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName)).onValueChangeUpdate(mainGroupField),
						mainGroupField.label("Main group").fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName)).onUpdate(this::populateMainGroupBox),
						Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
				//*/
				//*
				.add(Field.of(User::getName, User::setName, String.class).label("Name").enabled(false))
				.add(Field.of(User::getMaritalStatus, User::setMaritalStatus, MaritalStatus.class).label("Marital status"))
				.add(Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("Birth date"))
				.add(Field.of(User::getSalary, User::setSalary, BigDecimal.class).label("Salary"))
				.add(Field.of(User::getGroups, User::setGroups, Set.class).label("In groups").fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName)).onValueChangeUpdate(mainGroupField))
				.add(mainGroupField.label("Main group").fieldProvider(new ComboBoxProvider<>(User::getGroups, Group::getName)).onUpdate(this::populateMainGroupBox))
				.add(Field.of(User::getActive, User::setActive, Boolean.class).label("Active"))
				//*/
				//**
				.setFields(
						Field.of("name").label("The name"),
						Field.of("birthDate").label("The date of birth"),
						Field.of("email").label("The email"),
						Field.of("salary").label("The salary"),
						Field.of("phoneNumber").label("The phone number"),
						Field.of("maritalStatus").label("The marital status").fieldType(RadioButtonGroup.class),
						Field.of("groups").label("The groups").fieldProvider(new MultiSelectComboBoxProvider<>(u -> groupService.findAll(), Group::getName)).onValueChangeUpdate(mainGroupField2),
						mainGroupField2.label("The main group").fieldProvider(new RadioButtonGroupProvider<>(User::getGroups, Group::getName)).onUpdate(this::populateMainGroupBox),
						Field.of("active").label("Is it active?"))
				//*/
				.useBeanValidation()
				.build(user);

		var techForm = AutoGeneratedFormFactory.of(Technology.class)
				.replace("description", Field.of("description").label("Description").fieldType(TextArea.class))
				.useBeanValidation()
				.build(technologyService.findAll().get(3));

		var save = new Button("Save", e -> {
			try {
				if (userForm.isValid() && techForm.isValid()) {
					userService.save(userForm.getValue());
					technologyService.save(techForm.getValue());
					Notification.show("Saved: " + userForm.getValue());
					Notification.show("Saved: " + techForm.getValue());

				} else {
					Notification.show("Forms are not valid");
				}
			} catch (Exception ex) {
				Notification.show("Error: " + ex.getMessage());
				return;
			}
		});

		add(new VerticalLayout((Component) userForm, save), (Component) techForm);
		setSizeFull();
		UI.getCurrent().getPage().executeJs("window.applySystemTheme()");
	}

	private void populateMainGroupBox(AbstractField<?, Group> field, Object bean) {
		var hasItems = (HasListDataView<Group, ?>) field;
		var hasValue = (HasValue<?, Group>) field;
		User user = (User) bean;
		Group previousMainGroup = user.getMainGroup();
		hasItems.setItems(user.getGroups());
		if(user.getGroups().contains(previousMainGroup)) {
			hasValue.setValue(previousMainGroup);
		}
	}
}
