package org.vaadin.crudui.demo.ui.view;

import java.time.LocalDate;

import com.vaadin.flow.component.AbstractField;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.HasValue;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.splitlayout.SplitLayout.Orientation;
import com.vaadin.flow.data.provider.DataProvider;
import com.vaadin.flow.data.provider.HasListDataView;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.demo.entity.Group;
import org.vaadin.crudui.demo.entity.User;
import org.vaadin.crudui.demo.service.GroupService;
import org.vaadin.crudui.demo.service.UserService;
import org.vaadin.crudui2.form.CrudForm;
import org.vaadin.crudui2.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui2.form.impl.autogenerated.Field;
import org.vaadin.crudui2.layout.CrudLayout;
import org.vaadin.crudui2.layout.impl.SplitCrudLayout;
import org.vaadin.crudui2.list.CrudList;
import org.vaadin.crudui2.list.impl.GridList;

@Route(value = "playground2")
@JsModule("theme-handler.js")
@SuppressWarnings("null")
public class PlaygroundView2 extends VerticalLayout {

    public PlaygroundView2(UserService userService, GroupService groupService) {

        // @formatter:off
        CrudForm<User> userForm = AutoGeneratedFormFactory.of(User.class)
                .setFields(
                        Field.of(User::getName, User::setName, String.class).label("The name"),
                        Field.of(User::getBirthDate, User::setBirthDate, LocalDate.class).label("The date of birth"),
                        Field.of(User::getEmail, User::setEmail, String.class).label("The email"))
                .build(new User());
		// @formatter:on

        var grid = new Grid<User>();
        grid.addColumn(User::getName).setHeader("The name");
        grid.addColumn(User::getEmail).setHeader("The email");

        CrudList<User> userList = new GridList<>(grid);
        userList.setDataProvider(DataProvider.ofCollection(userService.findAll()));

        CrudLayout<User> layout = new SplitCrudLayout<>(Orientation.HORIZONTAL); // check vertical
        layout.setCrudList(userList);

        var save = new Button("Save", e -> {
            try {
                if (userForm.isValid()) {
                    User user = userForm.getValue();
                    boolean isNewUser = user.getId() == null;
                    userService.save(user);
                    if (isNewUser) {
                        layout.getCrudList().refreshAllItems();
                        Notification.show("User saved: " + user);
                    } else {
                        layout.getCrudList().refreshItem(user);
                        Notification.show("User updated: " + user);
                    }

                } else {
                    Notification.show("Form not valid");
                }
            } catch (Exception ex) {
                Notification.show("Error: " + ex.getMessage());
                ex.printStackTrace();
                return;
            }
        });

        layout.getCrudList().addItemSelectedListener(user -> {
            if (user != null) {
                userForm.setValue(user);
                layout.showCrudForm(userForm);
                layout.addFormActionComponent(save);
            } else {
                layout.hideForm();
            }
        });

        var create = new Button("Create", e -> {
            userForm.setValue(new User());
            layout.showCrudForm(userForm);
            layout.addFormActionComponent(save);
        });

        layout.addCrudActionComponent(create);

        add((Component) layout);
        expand((Component) layout);
        setSizeFull();
        // setPadding(false);
        UI.getCurrent().getPage().executeJs("window.applySystemTheme()");
    }

    private void populateMainGroupBox(AbstractField<?, Group> field, Object bean) {
        var hasItems = (HasListDataView<Group, ?>) field;
        var hasValue = (HasValue<?, Group>) field;
        User user = (User) bean;
        Group previousMainGroup = user.getMainGroup();
        hasItems.setItems(user.getGroups());
        if (user.getGroups().contains(previousMainGroup)) {
            hasValue.setValue(previousMainGroup);
        }
    }

}
