package org.vaadin.crudui.demo.ui.view;

import java.util.stream.Stream;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.router.Route;

import org.vaadin.crudui.Crud;
import org.vaadin.crudui.demo.entity.Technology;
import org.vaadin.crudui.demo.service.TechnologyService;
import org.vaadin.crudui.demo.ui.MainLayout;
import org.vaadin.crudui.form.impl.autogenerated.AutoGeneratedFormFactory;
import org.vaadin.crudui.form.impl.autogenerated.Field;
import org.vaadin.crudui.list.impl.GridList;

@Route(value = "tree", layout = MainLayout.class)
public class TreeView extends VerticalLayout {

    public TreeView(TechnologyService technologyService) {
        TreeGrid<Technology> treeGrid = new TreeGrid<>();
        treeGrid.setSizeFull();
        treeGrid.addHierarchyColumn(Technology::getName).setHeader("Name");
        treeGrid.addColumn(Technology::getVersion).setHeader("Version");
        treeGrid.addColumn(Technology::getLastPatchedAt).setHeader("Last Patched");

        Crud<Technology> crud = Crud.of(Technology.class)
                .list(GridList.of(Technology.class)
                        .grid(treeGrid))
                .form(AutoGeneratedFormFactory.of(Technology.class)
                        .fields(
                                Field.of("name").caption("Name"),
                                Field.of("version").caption("Version"),
                                Field.of("lastPatchedAt").caption("Last patched"),
                                Field.of("description").caption("Description"))
                        .captions("Create technology", "Edit technology")
                        .useBeanValidation())
                .onCreate(technologyService::save)
                .onRead(new AbstractBackEndHierarchicalDataProvider<Technology, Void>() {

                    @Override
                    public int getChildCount(HierarchicalQuery<Technology, Void> query) {
                        return (int) technologyService.findChildren(query.getParent()).count();
                    }

                    @Override
                    public boolean hasChildren(Technology tech) {
                        return technologyService.findChildren(tech).count() > 0;
                    }

                    @Override
                    protected Stream<Technology> fetchChildrenFromBackEnd(HierarchicalQuery<Technology, Void> query) {
                        return technologyService.findChildren(query.getParent());
                    }
                })
                .onUpdate(technologyService::save)
                .onDelete(technologyService::delete)
                .build();

        addAndExpand(crud);
        setSizeFull();
    }

}
