package org.vaadin.crudui;

import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.CustomComponent;
import org.vaadin.crudui.impl.form.AutoGeneratedVerticalCrudFormBuilder;
import org.vaadin.crudui.impl.layout.VerticalCrudLayout;

/**
 * @author Alejandro Duarte
 */
public abstract class AbstractCrudComponent<T> extends CustomComponent implements CrudComponent<T> {

    protected Class<T> domainType;
    protected CrudListener<T> crudListener;
    protected Object[] newFormVisiblePropertyIds;
    protected Object[] editFormVisiblePropertyIds;
    protected Object[] deleteFormVisiblePropertyIds;
    protected String[] newFormFieldCaptions;
    protected String[] editFormFieldCaptions;
    protected String[] deleteFormFieldCaptions;
    protected Object[] editFormDisabledPropertyIds;

    protected CrudLayout mainLayout;
    protected CrudFormBuilder<T> crudFormBuilder;

    public AbstractCrudComponent(Class<T> domainType, CrudListener<T> crudListener) {
        this(domainType, crudListener, new VerticalCrudLayout());
    }

    public AbstractCrudComponent(Class<T> domainType, CrudListener<T> crudListener, CrudLayout mainLayout) {
        this.domainType = domainType;
        this.crudListener = crudListener;
        this.mainLayout = mainLayout;
        BeanItemContainer<T> propertyIdsHelper = new BeanItemContainer<T>(domainType);
        crudFormBuilder = new AutoGeneratedVerticalCrudFormBuilder<T>();
        newFormVisiblePropertyIds = propertyIdsHelper.getContainerPropertyIds().toArray();
        editFormVisiblePropertyIds = propertyIdsHelper.getContainerPropertyIds().toArray();
        deleteFormVisiblePropertyIds = propertyIdsHelper.getContainerPropertyIds().toArray();

        setCompositionRoot(mainLayout);
        setSizeFull();
    }

    @Override
    public void setCaption(String caption) {
        mainLayout.setCaption(caption);
    }

    @Override
    public void showAllOptions() {
        showAddOption();
        showEditOption();
        showDeleteOption();
    }

    @Override
    public void setNewFormVisiblePropertyIds(Object... newFormVisiblePropertyIds) {
        this.newFormVisiblePropertyIds = newFormVisiblePropertyIds;
    }

    @Override
    public void setEditFormVisiblePropertyIds(Object... editFormVisiblePropertyIds) {
        this.editFormVisiblePropertyIds = editFormVisiblePropertyIds;
    }

    @Override
    public void setDeleteFormVisiblePropertyIds(Object... deleteFormVisiblePropertyIds) {
        this.deleteFormVisiblePropertyIds = deleteFormVisiblePropertyIds;
    }

    @Override
    public void setEditFormDisabledPropertyIds(Object... editFormDisabledPropertyIds) {
        this.editFormDisabledPropertyIds = editFormDisabledPropertyIds;
    }

    @Override
    public void setNewFormFieldCaptions(String... newFormFieldCaptions) {
        this.newFormFieldCaptions = newFormFieldCaptions;
    }

    @Override
    public void setEditFormFieldCaptions(String... editFormFieldCaptions) {
        this.editFormFieldCaptions = editFormFieldCaptions;
    }

    @Override
    public void setDeleteFormFieldCaptions(String... deleteFormFieldCaptions) {
        this.deleteFormFieldCaptions = deleteFormFieldCaptions;
    }

    @Override
    public CrudLayout getMainLayout() {
        return mainLayout;
    }

    @Override
    public void setCrudFormBuilder(CrudFormBuilder<T> crudFormBuilder) {
        this.crudFormBuilder = crudFormBuilder;
    }

    public CrudListener<T> getCrudListener() {
        return crudListener;
    }

}
