package org.vaadin.crudui.form.impl.form.factory;

import java.util.List;

import org.vaadin.crudui.crud.CrudOperation;
import org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory;

import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.HasValueAndElement;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;

/**
 * @author Alejandro Duarte
 */
public class GridLayoutCrudFormFactory<T> extends AbstractAutoGeneratedCrudFormFactory<T> {

    private int columns;
    private int rows;

    public GridLayoutCrudFormFactory(Class<T> domainType, int columns, int rows) {
        super(domainType);
        this.columns = columns;
        this.rows = rows;
    }

    @Override
    public Component buildNewForm(CrudOperation operation, T domainObject, boolean readOnly, ComponentEventListener<ClickEvent<Button>> cancelButtonClickListener, ComponentEventListener<ClickEvent<Button>> operationButtonClickListener) {
        FormLayout gridLayout = new FormLayout();
        gridLayout.setSizeFull();

        List<HasValueAndElement> fields = buildFields(operation, domainObject, readOnly);
        fields.stream()
                .forEach(field ->
                        gridLayout.getElement().appendChild(field.getElement()));

        Component footerLayout = buildFooter(operation, domainObject, cancelButtonClickListener, operationButtonClickListener);

        com.vaadin.flow.component.orderedlayout.VerticalLayout mainLayout = new VerticalLayout(gridLayout, footerLayout);
        mainLayout.setFlexGrow(1, gridLayout);
        mainLayout.setHorizontalComponentAlignment(Alignment.END, footerLayout);
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);

        return mainLayout;
    }

}
