package org.vaadin.crudui.impl.form;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.FieldGroupFieldFactory;
import com.vaadin.data.util.BeanItem;
import com.vaadin.server.Resource;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Notification;

/**
 * @author Alejandro Duarte
 */
public class AutoGeneratedVerticalCrudFormBuilder<T> extends AbstractAutoGeneratedCrudFormBuilder<T> {

    private FormLayout mainLayout = new FormLayout();

    public AutoGeneratedVerticalCrudFormBuilder() {
        this(DefaultCrudFieldFactory.get());
    }

    public AutoGeneratedVerticalCrudFormBuilder(FieldGroupFieldFactory fieldFactory) {
        super(fieldFactory);
        mainLayout.setSizeUndefined();
    }

    @Override
    public Component buildNewForm(T domainObject, Object[] visiblePropertyIds, Object disabledPropertyIds[], String[] fieldCaptions, boolean readOnly, String buttonCaption, String errorMessage, Resource buttonIcon, String buttonStyle, ClickListener saveButtonClickListener) {
        mainLayout.removeAllComponents();

        FieldGroup fieldGroup = new FieldGroup(new BeanItem<T>(domainObject));
        fieldGroup.setFieldFactory(fieldFactory);

        addFields(domainObject.getClass(), visiblePropertyIds, disabledPropertyIds, fieldCaptions, readOnly, fieldGroup, mainLayout);

        Button saveButton = new Button(buttonCaption, buttonIcon);
        saveButton.setStyleName(buttonStyle);
        mainLayout.addComponent(saveButton);
        saveButton.addClickListener(e -> {
            try {
                fieldGroup.commit();
                saveButtonClickListener.buttonClick(e);

            } catch (CommitException e1) {
                Notification.show(errorMessage);
            }
        });

        return mainLayout;
    }

    public FormLayout getMainLayout() {
        return mainLayout;
    }

}
