package org.vaadin.crudui.impl.form;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.FieldGroupFieldFactory;
import com.vaadin.data.util.BeanItem;
import com.vaadin.server.Resource;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickListener;

/**
 * @author Alejandro Duarte
 */
public class AutoGeneratedVerticalCrudFormBuilder<T> extends AbstractAutoGeneratedCrudFormBuilder<T> {

    private VerticalLayout mainLayout;

    private FormLayout formLayout = new FormLayout();

    private HorizontalLayout footerLayout = new HorizontalLayout();

    public AutoGeneratedVerticalCrudFormBuilder() {
        this(DefaultCrudFieldFactory.get());
    }

    public AutoGeneratedVerticalCrudFormBuilder(FieldGroupFieldFactory fieldFactory) {
        super(fieldFactory);
    }

    @Override
    public Component buildNewForm(T domainObject, Object[] visiblePropertyIds, Object disabledPropertyIds[], String[] fieldCaptions, boolean readOnly, String buttonCaption, String errorMessage, Resource buttonIcon, String buttonStyle, ClickListener buttonClickListener) {
        formLayout = new FormLayout();

        footerLayout = new HorizontalLayout();
        footerLayout.setSizeUndefined();

        mainLayout = new VerticalLayout(formLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setWidth("400px");
        mainLayout.setMargin(true);

        FieldGroup fieldGroup = new FieldGroup(new BeanItem<T>(domainObject));
        fieldGroup.setFieldFactory(fieldFactory);

        addFields(domainObject.getClass(), visiblePropertyIds, disabledPropertyIds, fieldCaptions, readOnly, fieldGroup, formLayout);

        Button button = new Button(buttonCaption, buttonIcon);
        button.setStyleName(buttonStyle);
        footerLayout.addComponent(button);

        button.addClickListener(e -> {
            try {
                fieldGroup.commit();
                buttonClickListener.buttonClick(e);

            } catch (CommitException e1) {
                Notification.show(errorMessage);
            }
        });

        return mainLayout;
    }

    public VerticalLayout getMainLayout() {
        return mainLayout;
    }

    public FormLayout getFormLayout() {
        return formLayout;
    }

    public HorizontalLayout getFooterLayout() {
        return footerLayout;
    }

}
