package org.vaadin.crudui.impl.form;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.FieldGroupFieldFactory;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Notification;
import org.vaadin.crudui.AbstractAutoGeneratedCrudFormFactory;
import org.vaadin.crudui.CrudFormConfiguration;

/**
 * @author Alejandro Duarte
 */
public class GridLayoutCrudFormFactory<T> extends AbstractAutoGeneratedCrudFormFactory<T> {

    private int columns;
    private int rows;

    public GridLayoutCrudFormFactory(FieldGroupFieldFactory fieldFactory, int columns, int rows) {
        this.columns = columns;
        this.rows = rows;
    }

    @Override
    public Component buildNewForm(T domainObject, CrudFormConfiguration configuration) {
        GridLayout mainLayout = new GridLayout(columns, rows);
        mainLayout.setSpacing(true);
        mainLayout.setSizeUndefined();
        mainLayout.removeAllComponents();
        mainLayout.setColumns(columns);
        mainLayout.setRows(rows);

        FieldGroup fieldGroup = new FieldGroup(new BeanItem<T>(domainObject));
        fieldGroup.setFieldFactory(fieldFactory);

        addFields(configuration, fieldGroup, mainLayout);

        Button button = new Button(configuration.getButtonCaption(), configuration.getButtonIcon());
        button.setStyleName(configuration.getButtonStyle());
        mainLayout.setRows(mainLayout.getRows() + 1);
        mainLayout.addComponent(button, 0, mainLayout.getRows() - 1);

        button.addClickListener(e -> {
            try {
                fieldGroup.commit();
                configuration.getButtonClickListener().buttonClick(e);

            } catch (CommitException e1) {
                Notification.show(configuration.getErrorMessage());
            }
        });

        return mainLayout;
    }

}
