package org.vaadin.crudui.impl.form;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.*;
import org.vaadin.crudui.AbstractAutoGeneratedCrudFormFactory;
import org.vaadin.crudui.CrudFormConfiguration;

/**
 * @author Alejandro Duarte
 */
public class GridLayoutCrudFormFactory<T> extends AbstractAutoGeneratedCrudFormFactory<T> {

    private int columns;
    private int rows;

    public GridLayoutCrudFormFactory(int columns, int rows) {
        this.columns = columns;
        this.rows = rows;
    }

    @Override
    public Component buildNewForm(T domainObject, CrudFormConfiguration configuration) {
        Button button = new Button(configuration.getButtonCaption(), configuration.getButtonIcon());
        button.setStyleName(configuration.getButtonStyle());

        HorizontalLayout footerLayout = new HorizontalLayout(button);
        footerLayout.setSizeUndefined();

        GridLayout gridLayout = new GridLayout(columns, rows);
        gridLayout.setWidth("100%");
        gridLayout.setSpacing(true);
        gridLayout.setSizeUndefined();
        FieldGroup fieldGroup = addFields(domainObject, configuration, gridLayout);

        configureButton(configuration, button, fieldGroup);

        VerticalLayout mainLayout = new VerticalLayout(gridLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);

        return mainLayout;
    }

}
