package org.vaadin.crudui.impl.form;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.*;
import org.vaadin.crudui.AbstractAutoGeneratedCrudFormFactory;
import org.vaadin.crudui.CrudFormConfiguration;

/**
 * @author Alejandro Duarte
 */
public class VerticalCrudFormFactory<T> extends AbstractAutoGeneratedCrudFormFactory<T> {

    @Override
    public Component buildNewForm(T domainObject, CrudFormConfiguration configuration) {
        FormLayout formLayout = new FormLayout();

        HorizontalLayout footerLayout = new HorizontalLayout();
        footerLayout.setSizeUndefined();

        VerticalLayout mainLayout = new VerticalLayout(formLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setWidth("400px");
        mainLayout.setMargin(true);

        FieldGroup fieldGroup = new FieldGroup(new BeanItem<T>(domainObject));
        fieldGroup.setFieldFactory(fieldFactory);
        addFields(configuration, fieldGroup, formLayout);

        Button button = new Button(configuration.getButtonCaption(), configuration.getButtonIcon());
        button.setStyleName(configuration.getButtonStyle());
        footerLayout.addComponent(button);

        button.addClickListener(e -> {
            try {
                fieldGroup.commit();
                configuration.getButtonClickListener().buttonClick(e);

            } catch (CommitException e1) {
                Notification.show(configuration.getErrorMessage());
            }
        });

        return mainLayout;
    }

}
